orbiting/backends

packages/assets/lib/returnImage.js

https://github.com/orbiting/republik-frontend/pull/82

fix: reenable webp

---

packages/assets/README.md
packages/assets/express/frontend.js
packages/assets/express/pdf.js
packages/assets/express/render.js
packages/assets/lib/renderUrl.js
packages/assets/lib/returnImage.js
servers/assets/.env.example

New Features
- proxy pdfs (for cdn caching)
- allow to set zoom factor for url rendering
- allow to convert gifs to pngs
- supersede https://github.com/orbiting/backends/pull/3

Assets Features for PDF

---

packages/assets/express/pdf.js

Missed the query string for `?images=0` ;)

fix(assets): forward pdf query string

---

packages/assets/lib/returnImage.js

Needed for PDF one click downloads (cross-origin)

feat(assets): forward Content-Disposition

---

packages/documents/package.json
servers/republik/package.json
yarn.lock

Related: 
https://github.com/orbiting/styleguide/pull/134
https://github.com/orbiting/styleguide/issues/133

fix: bump styleguide to support non-paragraph content in blockquotes and nesting of blockquotes

---

servers/publikator/.env.example
servers/publikator/graphql/resolvers/_mutations/publish.js
servers/publikator/graphql/resolvers/_mutations/unpublish.js
servers/publikator/lib/translations.json

This Pull Request allows to disable Publiaktor publishing or unpublishing actions via `ENV` flags. It allows editing and commiting documents but prevents publication of these.

feat(publikator): Disable publish, unpublish via ENV flags 

---

packages/search/lib/Documents.js

Episode documents are added to related repository IDs stack to then
being fetched.
This is rather swift, unpretentious fix and requires be revisited.

fix(search): Load series master document to retrieve episode documents

---

packages/base/lib/redis.js
packages/search/graphql/resolvers/_queries/search.js
packages/search/lib/Documents.js
packages/search/lib/cache.js
packages/search/lib/filters.js
packages/search/script/inserts/document.js
servers/publikator/graphql/resolvers/Commit.js
servers/publikator/graphql/resolvers/Repo.js
servers/publikator/graphql/resolvers/_mutations/publish.js
servers/publikator/graphql/resolvers/_mutations/uncommittedChanges.js
servers/publikator/graphql/resolvers/_mutations/unpublish.js
servers/publikator/lib/github/index.js
servers/publikator/lib/publicationScheduler.js

- always exclude contentString and resolved from _source
- imply/add type filter (based on schema) in filterReducer
- cache type === Documents queries in redis (3d TTL)
- expire keys in redis (commit, commit.document.mdast, mailchimpCampaignId, uncommittedChanges) (3 weeks TTL)

speed improvements for search

---

packages/search/graphql/schema-types.js
packages/search/lib/Documents.js
servers/republik/graphql/resolvers/_queries/employees.js
servers/republik/graphql/schema-types.js
servers/republik/graphql/schema.js

- add ids filter to Document schema. Allows to query for multiple userIds

refactor imprint

---

servers/republik/graphql/resolvers/Discussion/comments.js

This Pull Request ensures that a focused comment are put on top of a comment tree.
Before this Pull Request, top-level-comments with children did not bubble to the top but got focus attributes (e.g. background color) and were scrolled to. Yet, if hidden behind pagination horizon, got not shown at all.

fix(republik): Bubble focused comment with parents to very top of tree

---

docker-compose.yml

ci(docker): disable es disk size checking in docker image

---

packages/documents/graphql/resolvers/Document.js
packages/documents/graphql/resolvers/DocumentNode.js
packages/documents/graphql/schema-types.js
packages/documents/graphql/schema.js
packages/search/graphql/schema-types.js
packages/search/lib/Documents.js

Revert "Additions to search, documents query"

---

packages/access/lib/mail.js
servers/republik/graphql/resolvers/Comment.js
servers/republik/graphql/resolvers/Greeting.js
servers/republik/lib/translations.json

fix(access): handle new members without name

---

packages/base/package.json
packages/base/server.js
yarn.lock

Introduce all easy to implement security headers (skip CSP and HPKP for now).
HSTS initially just with a 24h window to test and ensure that no subdomain services breaks.

feat(security): wear helmet

---

servers/republik/modules/crowdfundings/express/paymentWebhooks.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/cancelMembership.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/generateMembership.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/payPledge.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/resolvePledgeToPayment.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/updatePayment.js
servers/republik/modules/crowdfundings/lib/generateMemberships.js
servers/republik/modules/crowdfundings/lib/payments/stripe/webhookHandler.js

This was successfully tested locally and with manually mocked Stripe responses. Will not merge, unless I can test this against the actual workflow, including Stripe webhook events.

Automatically cancel monthly memberships if upgraded to yearly 

---

packages/access/lib/mail.js
servers/republik/lib/translations.json

Adds additional merge variables for Mandrill email templates and updates subject line for followup email.

fix(access): Add additional merge vars with links

---

servers/publikator/lib/Discussion.js

Error on publish in Publikator:

fix: upsertDiscussion is not a function

---

packages/auth/loaders/User.js
packages/auth/loaders/index.js
packages/dataloader/index.js
packages/dataloader/package.json
packages/discussions/lib/loaders/Discussion.js
packages/discussions/loaders/Comment.js
packages/discussions/loaders/Discussion.js
packages/discussions/loaders/index.js
packages/discussions/package.json
servers/republik/graphql/resolvers/Comment.js
servers/republik/graphql/resolvers/Discussion/comments.js
servers/republik/graphql/resolvers/Discussion/userPreference.js
servers/republik/graphql/resolvers/_queries/discussion.js
servers/republik/graphql/resolvers/_queries/discussions.js
servers/republik/server.js
yarn.lock

an experimental integration of https://github.com/facebook/dataloader

dataloader setup and discussion integration

---

packages/auth/graphql/resolvers/_queries/me.js
packages/auth/graphql/resolvers/_queries/user.js
packages/auth/graphql/schema.js
packages/auth/lib/AccessToken.js
servers/republik/migrations/20181127231816-goal-memberships.js
servers/republik/migrations/sqls/20181127231816-goal-memberships-down.sql
servers/republik/migrations/sqls/20181127231816-goal-memberships-up.sql
servers/republik/modules/crowdfundings/graphql/resolvers/User.js
servers/republik/modules/crowdfundings/graphql/schema-types.js
servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
servers/republik/script/prolong/updateMailchimp.js

Membership extension wave 2

---

packages/formats/index.js
packages/formats/timeahead.js
servers/publikator/graphql/resolvers/_mutations/publish.js
servers/republik/.env.example
servers/republik/graphql/resolvers/Discussion/userWaitUntil.js
servers/republik/graphql/resolvers/_mutations/discussion/submitComment.js
servers/republik/lib/translations.json

For extreme cases where the community team needs to cool someone down.
The banned user will be informed via email. Generally we start with a week or less.
Unrelated change: add empty alt tag to open beacon.

Env Powered Discussion Bans

---

servers/republik/modules/crowdfundings/graphql/resolvers/User.js
servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
servers/republik/modules/crowdfundings/lib/Mail.js
servers/republik/modules/crowdfundings/lib/scheduler/givers.js
servers/republik/modules/crowdfundings/lib/scheduler/index.js
servers/republik/modules/crowdfundings/lib/scheduler/owners.js
servers/republik/modules/crowdfundings/lib/translations.json

Extension notify owners

---

packages/discussions/lib/Discussion.js
servers/publikator/lib/Discussion.js

close discussions via document.meta

---

servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/resolvePledgeToPayment.js

This Pull Request generate memberships (or membership periods) once a pledge is resolved.

fix(crowdfundings): Generate membership if necessary

---

servers/republik/modules/crowdfundings/lib/Mail.js
servers/republik/modules/crowdfundings/lib/scheduler/owners.js
servers/republik/modules/crowdfundings/lib/translations.json

This Pull Request sends an email on the very day a membership ends. Email is scheduled for 6:30 in the morning.
Added `sequenceNumber`, `cancel_url` and `grace_end_date` into template variables. Latter describes when an account is scheduled to be deactivated.

Send T-0 email

---

servers/republik/modules/crowdfundings/lib/scheduler/changeover.js

Code queryied for `succeedingMembershipId` instead of setting it.

fix(crowdfundings): Set succeedingMembershipId instead of querying it

---

servers/republik/modules/crowdfundings/lib/generateMemberships.js

Run `enforceSubscriptions` whenever `generateMemberships` is called

fix(crowdfundings): Enforce subscription on generateMembership

---

packages/assets/express/render.js

fix(assets): Check url var is defined

---

servers/republik/modules/crowdfundings/graphql/resolvers/Cancellation.js
servers/republik/modules/crowdfundings/graphql/resolvers/Membership.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/cancelMembership.js
servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/updateMembershipCancellation.js
servers/republik/modules/crowdfundings/graphql/schema-types.js
servers/republik/modules/crowdfundings/graphql/schema.js
servers/republik/modules/crowdfundings/lib/scheduler/winbacks.js

WIP Winback refactor 2

---

servers/republik/modules/crowdfundings/graphql/resolvers/_queries/adminUsers.js

Removing word distance all together in `adminUsers` query. Attempt to use word distance with word similarity on concatenated text failed; it returned unreliable results.

fix(crowdfundings): Remove word distance

---

packages/search/script/inserts/repo.js

Removes an unnecessary request for repository meta information.

fix(search): Remove unnecessary repo meta query

---

packages/collections/graphql/resolvers/_mutations/addDocumentToCollection.js
packages/collections/graphql/resolvers/_mutations/clearCollection.js
packages/collections/graphql/resolvers/_mutations/removeDocumentFromCollection.js
packages/collections/graphql/resolvers/_mutations/removeMediaProgress.js
packages/collections/graphql/resolvers/_mutations/upsertMediaProgress.js

Initialized tansactions were setup but never used.

fix(collections): Remove transactions in some resolvers

---

packages/access/lib/mail.js
packages/mail/templates/access_recipient_invitation.html

Relates https://github.com/orbiting/republik-frontend/issues/281

fix(mail): Include a granter's email address in invitation email

---

servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/updateUser.js

fixes https://github.com/orbiting/backends/issues/249

fix requesting email in updateUser mutation

---

packages/discussions/__tests__/integration.jest.js
packages/discussions/__tests__/queries.js
packages/discussions/graphql/resolvers/_mutations/unvoteComment.js
packages/discussions/graphql/schema.js
packages/discussions/lib/voteComment.js
packages/test/instance/index.js
servers/republik/server.js

[unvoteComment mutation](http://localhost:5000/graphiql/?query=mutation%20%7B%0A%20%20unvoteComment(id%3A%20%22ab5644f3-397d-4be4-beaa-3e7546dfc709%22)%20%7B%0A%20%20%20%20upVotes%0A%20%20%20%20downVotes%0A%20%20%20%20userVote%0A%20%20%7D%0A%7D%0A) removes the users vote.

feat(discussion): unvoteComment

---

packages/migrations/migrations/20190527051004-keep-query.js
packages/redirections/__test__/graphql/resolvers/Redirection.u.jest.js
packages/redirections/graphql/resolvers/Redirection.js
packages/redirections/graphql/resolvers/_mutations/addRedirection.js
packages/redirections/graphql/resolvers/_mutations/deleteRedirection.js
packages/redirections/graphql/resolvers/_mutations/updateRedirection.js
packages/redirections/graphql/resolvers/_queries/redirection.js
packages/redirections/graphql/resolvers/_queries/redirections.js
packages/redirections/graphql/schema-types.js
packages/redirections/graphql/schema.js
packages/redirections/lib/Redirections.js
packages/redirections/lib/Redirections.u.jest.js
packages/redirections/migrations/sqls/20190527051004-keep-query-down.sql
packages/redirections/migrations/sqls/20190527051004-keep-query-up.sql

feat(redirections): Expose API to CRUD redirections

---

packages/auth/__tests__/auth.int.jest.js
packages/auth/graphql/schema-types.js
packages/auth/lib/Sessions.js
packages/auth/lib/Users.js
packages/auth/lib/challenges/EmailCodeChallenge.js
packages/auth/lib/challenges/index.js
packages/auth/lib/translations.json
packages/auth/migrations/sqls/20190618105253-token-type-email-code-down.sql
packages/auth/migrations/sqls/20190618105253-token-type-email-code-up.sql
packages/mail/templates/signin_code.html
packages/migrations/migrations/20190618105253-token-type-email-code.js

feat(auth): Add an email code authentication challenge

---

servers/republik/script/finance/calculateKpis.js

Generates tab-separated values used by finance:
```
Entität	Monat	Zahlungsart	Aggregation	Anzahl	Betrag in CHF
PROJECT_R	2019-06	PAYMENTSLIP	Mitgliedschaften	88	88888.00
...
```

feat(republik): Add script to generate finance KPIs

---

servers/republik/graphql/resolvers/MembershipStats/count.js
servers/republik/graphql/resolvers/MembershipStats/periods.js
servers/republik/lib/memberStats.js

fix(republik): Return stats without PARKING_USER_ID environment variable

---

packages/search/lib/indexPgTable.js
packages/search/lib/inserts/document.js
packages/search/lib/inserts/repo.js
packages/search/lib/pullElasticsearch.js
packages/search/script/pullElasticsearch.js
servers/publikator/graphql/resolvers/_queries/repos.js
servers/publikator/graphql/schema.js
servers/publikator/lib/github/getRepos.js

Revert "feat(search): Filter repos while indexing repos, documents optionally"

---

servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/importPostfinanceCSV.js

* Postfinance did slightly adopt their CSV export. ("Gutschrift" becomes "Gutschrift in CHF")
* Remove EINZAHLUNGSSCHEIN filter
* Refactor field parsing and error handling

fix(crowdfundings): Refactor and update importPostfinanceCSV

---

packages/mail/express/render.js
packages/mail/lib/sendMailTemplate.js
packages/mail/package.json
yarn.lock

This Pull Request allows to render mail templates previews using handlesbars engine. Environment variables are merged with request query parameters.
`handlebars` is a development dependency as endpoint should never be available in production.

feat(mail): Render templates preview w/ handlebars engine

---

servers/republik/graphql/resolvers/MembershipStats/count.js
servers/republik/graphql/resolvers/MembershipStats/periods.js
servers/republik/lib/memberStats.js

fix: membershipStats not memberStats
fixes: https://github.com/orbiting/backends/pull/283#commitcomment-34915913

Fix fix broken stats

---

packages/cards/graphql/resolvers/Card.js
packages/cards/graphql/resolvers/CardGroup.js
packages/cards/graphql/resolvers/_mutations/claimCard.js
packages/cards/graphql/resolvers/_mutations/updateCard.js
packages/cards/script/insert-discussions.js
packages/cards/script/insert-statements.js
packages/search/lib/indexPgTable.js

* Wire comments in mutations claimCard, updateCard
* Implement Card.statement, CardGroup.discussion
* Add script to insert Card.payload.statement as a comment
* Lower batch size when submitting Postgres data into ElasticSearch

Wire comments w/ Cards and port existing data

---

packages/discussions/graphql/resolvers/Discussion/userPreference.js
packages/discussions/graphql/schema-types.js
packages/discussions/lib/Notifications.js

- feat(discussions): Respect notification option when notifiying subscribers
- fix(discussions): Allow `DiscussionPreferences.notifications` to be null

Respect notification option when notifiying subscribers

---

packages/discussions/graphql/resolvers/_queries/comments.js
packages/discussions/graphql/schema.js

* feat(discussions): Allow to query comments up until a specified depth
* fix(discussions): Return comment in hidden discussions if discussion IDs are provided

comments toDepth argument and return hidden discussion comments

---

packages/cards/graphql/schema-types.js
packages/cards/lib/cards.js

* feat(cards): Implement mustHave financing filter
* fix(cards): Retrieve focused cards even if filters are applied

Financing filter and fix card focus

---

packages/auth/lib/Users.js

Happened with type EMAIL_CODE. These payload are only unique per email address. Other types use uuids which are unlikely to collide.

fix(auth): prevent payload collision on authorize and deny

---

packages/mail/templates/membership_owner_prolong_notice_0.html
servers/republik/modules/crowdfundings/lib/scheduler/owners.js

This Pull Request is a temporary measure: It will pause membership owner prolong notice emails ("T-30, "T-7") and update email template on last one ("T-0").

fix(crowdfundings): Stop T-30, T-7 emails and revise T-0 email

---

packages/documents/lib/resolve.js
packages/search/lib/Documents.js
packages/search/lib/indices/documents.js
packages/voting/graphql/resolvers/QuestionTypeDocumentResult.js
servers/publikator/graphql/resolvers/_mutations/publish.js
servers/publikator/lib/cache/search.js

This Pull Request wires sections feature into all parts of republik, publikator servers.

Sections leftovers

---

packages/auth/lib/AccessToken.js
packages/mail/templates/payment_successful_tablebook.html
packages/mail/templates/pledge_tablebook.html
packages/translate/translations.json
servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
servers/republik/modules/crowdfundings/lib/CustomPackages/rules/earlyAdopterBonus.js
servers/republik/modules/crowdfundings/lib/CustomPackages/rules/endTooFarAway.js
servers/republik/modules/crowdfundings/lib/CustomPackages/rules/index.js
servers/republik/modules/crowdfundings/lib/utils.js

This Pull Request enables us to handle Goodie-only custom packages.
It also adds a custom package rule, `endTooFarAway`, which won't pass if there is no active membership or an active membership ends within a "horizon" date.
This Pull Request includes two new email templates dedicated to a pledge named `TABLEBOOK`.
Also, `CUSTOM_PLEDGE` access token scope expands to pledge package `TABLEBOOK`, too, and results in no regressions (e.g. already issues tokens still work).
**SQL**
```sql
BEGIN;
INSERT INTO "public"."packages"("id","crowdfundingId","name","createdAt","updatedAt","companyId","paymentMethods","isAutoActivateUserMembership","custom","rules","order","group")
VALUES
(E'ca911d63-04d7-4b87-94a0-b21cb55a75d5',E'fb546aaa-09e0-403e-8f42-c6ee2f9b437e',E'TABLEBOOK',E'2019-11-26 …
```

Enable TABLEBOOK pledge

---

packages/migrations/migrations/20191204080833-drop-disabled-package-option-flag.js
servers/republik/migrations/sqls/20191204080833-drop-disabled-package-option-flag-down.sql
servers/republik/migrations/sqls/20191204080833-drop-disabled-package-option-flag-up.sql

Succeeds https://github.com/orbiting/backends/pull/343

fix(republik): Remove disabled attribute on packageOptions table

---

servers/republik/graphql/resolvers/MembershipStats/evolution.js
servers/republik/graphql/schema-types.js

Attempt number 2 to have a more sane and sound `MembershipStats.evolution`.
This is a breaking change.

feat(republik): Add revised version of a more sane MembershipStats.evolution query

---

packages/discussions/graphql/resolvers/Discussion/comments.js

fix for https://github.com/orbiting/backends/pull/351

fix(discussion): respect depth of parent

---

packages/discussions/graphql/resolvers/Comment.js
packages/discussions/graphql/schema-types.js
packages/discussions/lib/Notifications.js
packages/embeds/graphql/resolvers/_mutations/refetchEmbed.js
packages/embeds/graphql/schema-types.js
packages/embeds/graphql/schema.js
packages/embeds/lib/fetchAndStore.js
packages/embeds/lib/linkPreview/index.js
packages/embeds/migrations/sqls/20200206105602-backoff-fetching-down.sql
packages/embeds/migrations/sqls/20200206105602-backoff-fetching-up.sql
packages/migrations/migrations/20200206105602-backoff-fetching.js

Backoff retries and fixes for CachedEmbeds (followup to #369)

---

packages/access/migrations/sqls/20200309104631-missing-indices-down.sql
packages/access/migrations/sqls/20200309104631-missing-indices-up.sql
packages/auth/migrations/sqls/20200309110510-missing-indices-down.sql
packages/auth/migrations/sqls/20200309110510-missing-indices-up.sql
packages/discussions/migrations/sqls/20200309105709-missing-indices-down.sql
packages/discussions/migrations/sqls/20200309105709-missing-indices-up.sql
packages/migrations/migrations/20200309104631-missing-indices.js
packages/migrations/migrations/20200309105709-missing-indices.js
packages/migrations/migrations/20200309110510-missing-indices.js

add missing indices based on most time consuming, most frequently invoked and slowest execution time of postgres diagnose.

add missing indices

---

packages/search/graphql/resolvers/_queries/search.js

feat: don't restrict docs of formats in DOCUMENTS_UNRESTRICTED_CHILDREN_REPO_IDS

---

packages/discussions/package.json
packages/documents/package.json
servers/republik/package.json
yarn.lock

The styleguide now renders a special logo for covid ;)

chore: bump styleguide

---

packages/discussions/lib/Notifications.js
packages/subscriptions/graphql/resolvers/_mutations/sendTestNotification.js
packages/subscriptions/graphql/resolvers/_mutations/sendTestPushNotification.js
packages/subscriptions/graphql/schema.js
servers/publikator/lib/Notifications.js

- [sendTestPushNotification](http://localhost:5000/graphiql/?query=mutation%20%7BsendTestPushNotification%7D)
- [sendTestNotification](http://localhost:5000/graphiql/?query=mutation%20%7B%0A%20%20sendTestNotification(commentId%3A%20%22837cd81c-b412-4141-a39f-e3589587c883%22%2C%20repoId%3A%20%22republik-dev%2Farticle-scheduled-notification-test%22)%0A%7D%0A)

feat: mutations to send test notifications

---

servers/republik/script/gdpr/extractPersonalData.js

This Pull Request adds a working draft of a script to export personal data.

chore(republik): Add script to extract personal data

---

README.md
app.json
docker-compose.republik-backend.yml
lambdas/chromium/.env.example
lambdas/chromium/README.md
lambdas/chromium/screenshot.js
packages/access/lib/constraints/granterBlocklist.js
packages/access/lib/constraints/granterDenylist.js
packages/access/lib/constraints/index.js
packages/access/lib/constraints/recipientBlocklist.js
packages/access/lib/constraints/recipientDenylist.js
packages/assets/README.md
packages/assets/express/s3.js
packages/base/server.js
packages/maillog/graphql/resolvers/MailLogRecord.js
packages/translate/translations.json
servers/assets/.env.example
servers/assets/README.md
servers/assets/server.js
servers/publikator/.env.example
servers/republik/.env.example
servers/republik/docker-compose.yml

replace blacklist -> denylist, whitelist -> allowlist
affected ENVS:
```
lambda:
URL_WHITELIST
backends:
CORS_WHITELIST_URL
AWS_BUCKET_WHITELIST
```

Black Lives Matter

---

packages/discussions/lib/Notifications.js

basically a resurrection and modernization of 5a7976c
featuring optional chaining and nullish coalescing in one and the same [line](https://github.com/orbiting/backends/pull/453/files#diff-09ab43947bba51ac919009fbf7776378R171) :tada: 
before deploy:

Subscribe authors / users (comments)

---

packages/gsheets/graphql/resolvers/_queries/employees.js
packages/gsheets/graphql/schema.js

[query](http://api.republik.test/graphiql/?query=%7Bemployees(onlyPromotedAuthors%3A%20true)%20%7B%0A%20%20group%0A%20%20subgroup%0A%20%20name%0A%20%20title%0A%20%20greeting%0A%7D%7D)

feat: filter employees for promotedAuthors

---

servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/appendPeriod.js

Will post a Slack message when `mutation appendPeriod` is successful:

feat(crowdfundings): Add Slack post whenever a period is appended

---

packages/discussions/lib/Discussion.js
servers/publikator/lib/Discussion.js
servers/publikator/lib/Document.js
servers/publikator/lib/PublicationScheduler.js

fix: upsertDiscussion only at time of publish

---

servers/publikator/lib/cache/upsert.js

missed to update in https://github.com/orbiting/backends/pull/467

fix: repo milestones not cached (fix upgrade elastic)

---

README.md

Improve description about component division

---

servers/republik/modules/crowdfundings/graphql/resolvers/User.js
servers/republik/modules/crowdfundings/lib/AutoPay.js

- Wire auto payment suggestion to plausable payment methods
- Determine prolong date using auto payment suggestion
- Handle missing pledge payment
Closes #469

Changes to ensure smooth 3rd 🌊

---

packages/styleguide/package.json
servers/publikator/lib/mailchimp/updateCampaign.js
servers/republik/package.json
yarn.lock

Depends on https://github.com/orbiting/styleguide/pull/315 (waiting on final CR-Feedback)
Also: Sets `to_name` on MailChimp-Campaigns which will hopefully also help with Spam-Filters.

Bump Styleguide for Variables for Documents

---

packages/republik-crowdfundings/__tests__/helpers.js
packages/republik-crowdfundings/__tests__/stripe.int.jest.js
packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
packages/republik-crowdfundings/graphql/resolvers/_mutations/reclaimPledge.js
packages/republik-crowdfundings/lib/payments/stripe/addSource.js
packages/republik-crowdfundings/lib/payments/stripe/mergeCustomers.js

The important lib: `packages/republik-crowdfundings/lib/payments/stripe/mergeCustomers.js`

fix: merge stripe customers and fix reclaimPledge, mergeUsers

---

packages/republik-crowdfundings/graphql/resolvers/User.js
packages/republik-crowdfundings/lib/AutoPay.js
packages/republik-crowdfundings/lib/paymentSource.js
packages/republik-crowdfundings/lib/scheduler/owners.js

Fix: scheduler with missing credit cards

---

packages/republik-crowdfundings/lib/AutoPay.js
packages/republik-crowdfundings/lib/paymentSource.js
packages/republik-crowdfundings/lib/scheduler/owners.js

Fix missing await and temporarily comment out critical code, as this has not been tested.
An issue has been created, in order not to forget to un-comment the critical code: https://github.com/orbiting/backends/issues/504

Fix missing await

---

packages/discussions/graphql/resolvers/Comment.js
packages/discussions/graphql/resolvers/_mutations/setDiscussionPreferences.js
packages/discussions/graphql/resolvers/_mutations/submitComment.js
packages/discussions/lib/discussionPreferences.js
packages/discussions/lib/index.js
packages/discussions/lib/setDiscussionPreferences.js
packages/discussions/migrations/sqls/20200828033421-identifiable-anonymous-down.sql
packages/discussions/migrations/sqls/20200828033421-identifiable-anonymous-up.sql
packages/migrations/migrations/20200828033421-identifiable-anonymous.js
packages/translate/translations.json

Done: 
* If user sets comments to anonymous an anonymous diff. is added to db entry
* Differentiator will be displayed at comments
TODO:
* edge cases

Anonymous comment differentiator

---

packages/slack/lib/SlackGreeter.js

Allow bot's to post greetings.

feat(slack): accept bot greetings

---

packages/publikator/graphql/resolvers/_mutations/commit.js
packages/translate/translations.json

Translations missing - can you grant me access to the backend translations file @tpreusse ?

Validate presence of title and slug in template repo

---

packages/publikator/graphql/resolvers/_queries/reposSearch.js
packages/publikator/graphql/schema-types.js
packages/publikator/graphql/schema.js
packages/publikator/lib/cache/search.js
packages/publikator/lib/cache/upsert.js

http://localhost:5000/graphiql/?operationName=repoListSearch&query=query%20repoListSearch%20%7B%0A%20%20repos%3A%20reposSearch(first%3A%2010%2C%20dateRange%3A%20%7B%20from%3A%20%222020-12-07%22%2C%20before%3A%20%222020-12-14%22%7D)%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20meta%20%7B%0A%20%20%20%20%20%20%20%20publishDate%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20latestCommit%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20date%0A%20%20%20%20%20%20%20%20message%0A%20%20%20%20%20%20%20%20author%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20document%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20meta%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20template%0A%20%20%20%20% …

Calendar view

---

packages/mail/templates/membership_owner_feedback.html
packages/mail/templates/membership_owner_feedback.txt
packages/republik-crowdfundings/graphql/resolvers/_mutations/cancelMembership.js
packages/republik-crowdfundings/graphql/resolvers/_mutations/reactivateMembership.js
packages/republik/lib/slack.js

Two small requests bei community team.
Mark in slack when cancellation are done by support team. And fix access sharing promo in 3 weeks happiness mail.

Small text changes

---

packages/documents/graphql/schema-types.js
packages/documents/lib/process.js
packages/publikator/graphql/resolvers/_mutations/commit.js

Support `meta.series.logo` and `data.formatLogo` in teasers.

feat(documents): series logo and teaser format logo

---

packages/publikator/lib/phases.ts

fix(publikator): Put published and re-scheduled repos in scheduled phase

---

packages/search/lib/indexPgTable.js
packages/search/lib/inserts/comment.js
packages/search/lib/inserts/user.js

Each update, insert or delete dispatches a Postgres notification which application is subscribed to
will update search indices accordingly.
Before this change, all related pgdb tables were loaded into memory (users, comments, discussions)
to gather data for search indices.
It now queries payloads per insert type individually. This will slow down bulk index
("pulling elasticsearch") but increase health of production app.

fix(search): Query payloads per insert individually

---

packages/documents/lib/process.js

Same code but not returning anything while visting (which is neither need nor was it intentional).

fix(documents): Fix formatLogo processing

---

servers/assets/public/robots.txt
servers/assets/server.js

feat(assets): add robots.txt

---

packages/documents/graphql/schema-types.js

make all the various fields of this feature queriable

Sharegenerator

---

packages/mail/templates/payment_successful_tablebook.html
packages/mail/templates/payment_successful_tablebook.txt
packages/mail/templates/pledge_tablebook.html
packages/mail/templates/pledge_tablebook.txt
packages/republik-crowdfundings/lib/CustomPackages/rules/hasAccompliceRole.js
packages/republik-crowdfundings/lib/CustomPackages/rules/index.js

- fix(republik-crowdfundings): Add CustomPackage rule hasAccompliceRole
- fix(mail): Change delivery notice for tablebooks

Tablebook Disposal

---

packages/republik-crowdfundings/lib/scheduler/owners/charging.js

Before-last-autopay-failed-notice transactional was missing a date ("last attempt on [missing date]")

fix(republik-cf): fix reminder auto payment when credit card is invalid

---

packages/documents/graphql/resolvers/Document.js
packages/documents/graphql/schema-types.js
packages/documents/lib/resolve.js
packages/publikator/graphql/resolvers/Meta.js
packages/publikator/graphql/resolvers/_mutations/publish.js
packages/publikator/lib/Document.js
packages/publikator/package.json
packages/search/lib/Documents.js
packages/search/lib/indices/documents.js
yarn.lock

powers https://github.com/orbiting/republik-frontend/pull/594 and https://github.com/orbiting/publikator-frontend/pull/289

Precipitously improved series nav

---

.gitignore
package.json
packages/cards/migrations/sqls/20210520083239-drop-card-documents-down.sql
packages/cards/migrations/sqls/20210520083239-drop-card-documents-up.sql
packages/migrations/migrations/20210520082541-repoid-as-foreignkey.js
packages/migrations/migrations/20210520083239-drop-card-documents.js
packages/publikator/loaders/Commit.ts
packages/publikator/loaders/Repo.ts
packages/publikator/migrations/sqls/20210520082541-repoid-as-foreignkey-down.sql
packages/publikator/migrations/sqls/20210520082541-repoid-as-foreignkey-up.sql
packages/publikator/package.json
packages/publikator/script/copyImages.ts

Link repoIds, drop cardDocuments, add copyImages script

---

.gitignore
packages/republik/script/fixMissingPortraitUrls.ts

This Pull Requests adds a script which checks if a users `portraitUrl` is fetchable. If it isn't, it set `portraitUrl` to `null`.

chore(republik): Add script to fix portraitUrls

---

packages/mail/lib/getNewsletterSettings.js
packages/mail/lib/updateNewsletterSubscription.js
packages/republik/graphql/resolvers/_mutations/resubscribeEmail.js
packages/republik/graphql/resolvers/_mutations/updateNewsletterSubscription.js
packages/republik/graphql/schema-types.js
packages/republik/graphql/schema.js

... and with that also remove newsletter status handling in `updateNewsletterSubscription` mutation

Add mutation to resubscribe email to mailchimp

---

packages/republik-crowdfundings/lib/scheduler/owners.js

fixes https://github.com/orbiting/backends/issues/504

actually set auto pay to false if data is missing

---

packages/discussions/graphql/resolvers/Comment.js
packages/utils/__snapshots__/mdastCollapseLink.u.jest.js.snap
packages/utils/index.js
packages/utils/mdastCollapseLink.js
packages/utils/mdastCollapseLink.u.jest.js
packages/utils/package.json
yarn.lock

It will shorten (or collapse) exceedingly long links in `Comment.preview` prop.
fixes #257

Collapse links in Comment.preview

---

packages/republik-crowdfundings/lib/scheduler/importPayments.ts

* removes conversion to utf-8 and trimming of `avisierungstext` in `exists` method
(there is some formatting noise, bit surprised about that, but I guess it's fine)

remove legacy stuff in exists method of importPayments

---

packages/invoices/express/index.ts

returns error response if any error happens within `pdfReqHandler` method

better error handling when generating invoices/paymentslips

---

packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js

solves https://github.com/orbiting/backends/issues/517

mergeUsers: add slack notification if anything goes wrong

---

packages/republik/graphql/resolvers/_mutations/updateMe.js

* fix check when user who is candidating for GR wants to change portrait image
can be tested on love

(republik) fix check in updateMe.js 

---

packages/publikator/lib/phases.ts
packages/translate/translations.json

relates to https://github.com/orbiting/publikator-frontend/pull/301
see https://www.notion.so/republikmagazin/Neue-Repo-Phase-vorbereiten-3941081d66e5432c9afdabda4ff67b9d

fix(publikator): Introduce new repo phase "tribe chief"

---

packages/base/server.js
servers/assets/public/.well-known/security.txt
servers/graphql/public/.well-known/security.txt

Serve /.well-known/security.txt on graphql and assets server:
```
Contact: mailto:security@republik.ch
Contact: https://www.republik.ch/security
Expires: 2023-12-31T23:59:00.000Z
```

Serve /.well-known/security.txt

---

packages/discussions/graphql/resolvers/Discussion/comments.js

* comments sorted by votes only after 72 hours not 24 hours

(discussion) increase threshold for resolved order of comments

---

package.json
packages/cards/script/import-smartvote-data.js
packages/discussions/lib/Notifications.js
packages/documents/lib/html.js
packages/styleguide/index.js
packages/styleguide/package.json
packages/styleguide/scripts/sg_link.sh
packages/styleguide/scripts/sg_unlink.sh
yarn.lock

Update Styleguide imports to accommodate the changes made in the tech refresh.
(Optional)
- Improve styleguide link- and unlink- scripts

Update Styleguide imports to work with the newest major version

---

packages/mail/templates/membership_owner_prolong_notice.html
packages/mail/templates/membership_owner_prolong_notice.txt

* adds fondue text to T-30 membership prolong mail
(Deploy not before Friday Dec 10th)

(mail) add fondue teaser text to T-30

---

packages/republik-crowdfundings/lib/scheduler/owners.js
packages/republik-crowdfundings/lib/scheduler/owners/charging.js
packages/republik-crowdfundings/lib/scheduler/owners/mailings.js

This Pull Request uses `PgDb.queryInBatches` to speed up owners scheduler and reduce memory und CPU load.

refactor(republik-crowdfundings): Use PgDb.queryInBatches

---

packages/auth/graphql/resolvers/User.js
packages/auth/graphql/schema-types.js
packages/auth/migrations/sqls/20211214192618-remove-eventlog-down.sql
packages/auth/migrations/sqls/20211214192618-remove-eventlog-up.sql
packages/migrations/migrations/20211214192618-remove-eventlog.js
packages/migrations/script/create.js
packages/republik-crowdfundings/graphql/resolvers/_mutations/deleteUser.js
packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
packages/republik/script/gdpr/deleteLocal.js
packages/republik/script/gdpr/extractPersonalData.js

This Pull Request drops `eventLog` table and `User.eventLog`.

feat(auth): Remove eventLog

---

packages/mail/templates/membership_owner_prolong_notice.html
packages/mail/templates/membership_owner_prolong_notice.txt

This Pull Request drops Fondue hint in T-30 transactional.

chore(mail): Drop fondue hint in T-30 transactional
