- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/reactivateMembership.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/submitPledge.js
- servers/republik/modules/crowdfundings/lib/activateYearlyMembership.js
- servers/republik/modules/crowdfundings/lib/payments/stripe/webhooks/customerSubscription.js
- servers/republik/script/fixInactiveYearlyMemberships.js
- activate inactive yearly if available on monthly end (on stripe webhook)
- based on a scripted added on master: https://github.com/orbiting/backends/commit/3747a4bc4af0890d600b556ba270275b2bdd077f
- sync nl subscriptions in various places
- rm reduced membership purchase restriction
switching from a monthly to a reduced yearly should be allowed. generally the restriction is somewhat arbitrary.
> Fixes before stitches

- packages/documents/graphql/resolvers/Document.js
- packages/documents/lib/process.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/reactivateMembership.js
- servers/republik/modules/crowdfundings/lib/translations.json
Prevent user who switched to yearly membership from re-activation their monthly abo (implemented generically—no point in activating two).
> Restrict Monthly Activation & Members Only Zones

- packages/auth/seeds/email_templates/signin.html
Already updated on mailchimp, major changes:
- visible button instead of low-profile text link
- Republik-style typography instead of ProjectRs grey Times New Roman
- more robust inline styles
Apple Mail screenshot:
> fix: auth confirmation email with visible button and improved inline styling

- servers/publikator/README.md
- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/lib/mailchimp/createCampaign.js
Disable all MailChimp tracking and add a Piwik open beacon.
I followed this guide: https://matomo.org/faq/how-to/faq_25454/ and customised it for our Piwik setup.
The most controversial is the `uid`: https://github.com/orbiting/backends/commit/0993b927d8933a0f99b334fd8a162cb891fd9be3
However without an `uid` it will be impossible to calculate an open rate. We could pseudo anonymise the `uid` but since it needs to be stable we would always be able to resolve it—whats the point?
> Email Tracking

- packages/assets/lib/returnImage.js
… because it is apparently not supported by quite a few mobile devices. And Firefox.
https://piratinnen.slack.com/archives/C8T08FYFR/p1520097182000083
The diff also contains some stuff that I had to fix in order for standard to swallow the commit. Don't we all use the same config?
> fix($browser): disable webp

- packages/auth/lib/signIn.js
- packages/auth/package.json
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/updateEmail.js
- yarn.lock
Frontend PR: https://github.com/orbiting/republik-frontend/pull/83
> fix: swap "isemail" with "validator" to match frontend validation

- packages/documents/graphql/schema-types.js
- packages/documents/lib/meta.js
- packages/documents/lib/resolve.js
Kicking off backend changes for storing a reference to an audio version of an article. The current plan is to have input fields in an article's meta section for entering a URL of a previously uploaded mp3 and optionally aac and/or ogg. These may eventually turn into file upload fields.
Publikator PR: https://github.com/orbiting/publikator-frontend/pull/140
Frontend PR: https://github.com/orbiting/republik-frontend/pull/84
> feat: audioSources

- packages/documents/package.json
- yarn.lock
We had this error since moving to node 8.10:
```
error @project-r/styleguide@5.52.1: The engine "node" is incompatible with this module. Expected version "8.9.x".
error An unexpected error occurred: "Found incompatible module".
```
I relaxed the node version requirement (anything gte 8.9) in the [styleguide](https://github.com/orbiting/styleguide/releases/tag/v5.71.5).
> fix(setup): bump styleguide with relaxed node version requirement

- servers/republik/modules/crowdfundings/express/paymentWebhooks.js
- servers/republik/modules/crowdfundings/lib/payments/postfinance/payPledge.js
disclaimer: no tests because we don't have any tests for POSTFINANCE yet, and setting all of this up would blast the scope of this bugfix.
> payPledge via webhook for postfinance

- packages/documents/package.json
- servers/republik/graphql/resolvers/Comment.js
- servers/republik/graphql/resolvers/Discussion/comments.js
- servers/republik/graphql/schema-types.js
- servers/republik/lib/Notifications.js
- servers/republik/lib/remark.js
- servers/republik/package.json
- yarn.lock
resolves: https://github.com/orbiting/backends/issues/23
TODOs
> markdown in comments

- packages/auth/lib/Sessions.js
- packages/auth/lib/signIn.js
- packages/auth/package.json
- packages/base64u/index.js
- packages/base64u/index.test.js
- packages/base64u/package.json
- yarn.lock
Ensures `email` query parameter in verification URL is encoded as base64 in an url-safe manner and ensures `emailFromQuery` in `Session::sessionByToken()` is a plain string.
URLs containin `email=<email>` or `email=<urlencoded email>` instead of `email=<base64-encoded email>` let to double-encoding conflicts in some email clients, and resulted in URLs being invalid:
`heidi@wiese.tld` is encoded to `heidi%40wiese.tld` (`@` => `%40`). Some email clients would re-encode and generate a link with `heidi%2540wiese.tld` (`%` => `%25`).
⚠️ This is a breaking change and requires https://github.com/orbiting/republik-frontend/pull/101 ~to be merged an deployed first.~ Deployed.
Introduces [urlsafe-base64](https://www.npmjs.com/package/urlsafe-base64) as a dependency.
> fix(auth): Encode/decode email in verification URL

- packages/auth/lib/Sessions.js
This Merge Requets reverts "fail safe" about having a decoded `emailFromQuery` as email value passed is to be expected an email address, not a potentially base64, URL-safe encoded email address.
> fix(auth): Remove email base64 decoding

- servers/republik/graphql/resolvers/_queries/statements.js
before the `focus` (internally called `firstId`) came in a random spot
afterwards it is guaranteed that it comes first
> fix(Statements): obey correct order of users

- packages/assets/README.md
- packages/assets/express/frontend.js
- packages/assets/lib/renderUrl.js
- servers/assets/.env.example
- servers/assets/server.js
set BASIC_AUTH_USER, BASIC_AUTH_PASS to secure the api itself.
set FRONTEND_BASIC_AUTH_USER, FRONTEND_BASIC_AUTH_PASS to authenticate to the frontend (/render, /frontend)
> split basic auth config in assets package

- packages/mail/MailchimpInterface.js
MailChimp stores, however added, email addresses all lower-cased. This Pull Request makes sure `MailchimpInterface` is querying MailChimp API with a MD5-hashed, _lower-cased_ email address.
It fixes a bug in which we did query API with a case-sensitive email address and did not receive any results.
> fix(mail): Query with lower-cased, hashed email address

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/indices/comments.js
- packages/search/lib/indices/documents.js
- packages/search/lib/indices/users.js
- servers/republik/graphql/resolvers/_mutations/requestPreview.js
A preview newsletter is a `Document` in ElasticSearch, having `meta.template:editorialNewsletter` set but not in feed (`meta.feed:false`). Default search query does not return newsletters.
`getDocument` can't, and should neither be allowed, to retrieve preview email via `repoId`.
This Pull Request changes [Document filter query to allow returning preview newsletter](dd56238), set in environment variable `PREVIEW_MAIL_REPO_ID`.
It does [functionalize `filters`](51fec56) (like `rolebasedFilter` is already)
> Fix: Sending preview email did not work

- .travis.yml
- docker-compose.yml
- packages/base/package.json
- packages/search/package.json
- yarn.lock
This Pull Request updates [`elasticsearch` dependency to 15.0.0](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog.html) and uses [ElasticSearch 6.3](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.3.0.html) (and Kibana 6.3) when testing and in docker-compose file.
> Bump elasticsearch, use ES 6.3

- servers/republik/migrations/20180703153921-package-options-vat.js
- servers/republik/migrations/sqls/20180703153921-package-options-vat-down.sql
- servers/republik/migrations/sqls/20180703153921-package-options-vat-up.sql
- servers/republik/modules/crowdfundings/graphql/resolvers/Pledge.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/generateMembership.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/submitPledge.js
- servers/republik/modules/crowdfundings/graphql/schema-types.js
This Pull Request adds a `vat` attribute to `packageOptions` table. It's value is an integer. 100 would represent 1%. Default value is 0.
When creating a pledge and it's options, VAT value of package option is copied into `vat` attribute in `pledgeOptions` table.
It further exposes VAT value in GraphQL `PackageOption` type.
This enables to create invoices (upcoming changes), taking VAT into account.
A migration for existing pledge options is run manually.
> Value-Added-Tax for package options

- packages/search/lib/Documents.js
An article may have one published document and a scheduled document.
Query is build in a manner that can not "distinct" that at the moment.
As an example: We query database for max 9 documents (ES `size` parameter) as we are looking up 9 repositories. A fair but wrong assumption. 1 repository may however return up to 2 documents. This fix multiplies expected result by 2, so we'd expect up to 18 documents for 9 repositories.
> fix(search): Expect n * 2 related documents

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/Documents.js
- packages/search/lib/cache.js
Cache should also be invalidated when a document is scheduled to publish. So far cache got only invalidated when a document's status was supposed to change it's `__state` to published, prepublished.
> fix(search): Invalidate cache when scheduling a document to publish

- packages/documents/package.json
- servers/republik/package.json
- yarn.lock
Styleguide Bump for: https://github.com/orbiting/styleguide/pull/148
Fixes this:
@patrickvenetz is `republik-publikator-api` deploy-able? Is it ok if I push this out?
> fix(newsletter): bump styleguide, skip empty covers

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/utils.js
- packages/search/script/pullElasticsearch.js
Creates search tracking indices with this pattern: `republik-searches-<YYYY-mm-dd>`. Data can be aggregated with wildcarded index queries like `republik-searches-*` (or via Kibana index patterns).
This prevents indices to grow too big to handle and allows to remove data over time more easily by removing a date range.
It also adds aggregation results, and user roles. Latter should allow to separate internal traffic from external.
> feat(search): Create search tracking index per day

- servers/republik/graphql/resolvers/_mutations/discussion/editComment.js
- servers/republik/graphql/resolvers/_mutations/discussion/submitComment.js
- servers/republik/graphql/resolvers/_mutations/discussion/unpublishComment.js
- servers/republik/lib/slack.js
This Pull Request respects current anonymize settings when posting notification about new, edited or unpublished comments to Slack.
Also beautified Slack postings, including links to profiles, discussions and emojis.
- 💌 A new comment
- ✏️ An edited comment
- 🚮 An unpublished comment
- ☝️ A comment unpublished by an admin user
> feat(republik): Respect anon when posting to slack

- packages/search/lib/Documents.js
- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/script/db-migrate-all.js
- servers/republik/script/db-migrate-all.js
This Pull Request places resolved meta information into `resolved.meta` instead of `resolved` when a document is published. Latter is not indexed and hence was not queryable.
`resolved` data servers mainly search to retrieve documents if e.g. a format title matches.
__Before, a document__
```
{
[...]
"resolved": {
"format": {
"meta": {
"template": "format",
"repoId": "republik/format-example",
"description": "",
"title": "Example Format"
}
}
},
[...]
}
```
`resolved.format` is not mapped and not indexed. This data is not queryable.
__After, a document__
```
{
[...]
"resolved": {
"meta": {
"format": {
"meta": {
"template": "format",
"repoId": "republik/format-example",
"description": "",
"title": "Example Format"
}
}
}
},
[...]
}
```
`resolved.meta.format` is mapped and hence indexed and …
> Fix: Add resolved into indexed node

- packages/documents/graphql/schema-types.js
We need this in Publikator for filling the feuilleton subject (Spitzmarke) when importing teaser content from an article on the feuilleton front. It's analogue to `description` which is used for filling the lead of the teaser.
Publikator already writes it, e.g.
https://github.com/republik-test/article-spitzmarke-ahoi/blob/master/article.md
> fix(meta): add subject to document meta data

- packages/documents/graphql/resolvers/Document.js
- packages/documents/graphql/schema-types.js
- packages/documents/graphql/schema.js
- packages/search/graphql/schema-types.js
- packages/search/lib/Documents.js
This Pull Request adds ability to query for `Document` entities which belong to a "format" or "dossier", like so:
```gql
{
documents(hasFormat: true) {
nodes {
meta {
title
path
format {
meta {
title
path
}
}
}
}
}
}
```
`hasFormat` and `hasDossier` are available as flags in `documents` query and as filters in `search` query:
```gql
{
search (filter: {hasFormat: true}) {
nodes {
entity {
... on Document {
meta {
title
path
format {
meta {
title
path
} 
}
}
}
}
}
}
}
```
This Pull Request also reinstates broken `nodes.linkedDocuments` for `Document` entities to query for children documents, like so:
```gql
{
documents(template: "format") {
totalCount
nodes {
meta {
title
path
}
linkedDocuments {
totalCount
}
}
}
}
```
Linked documents are available as full blown `Document` entities, like …
> Additions to search, documents query

- packages/documents/graphql/schema-types.js
This Pull Request exposes `prepublication` prop in `Document` type which reveals if a document has been pre-published internally.
> feat(documents): Expose prepublication prop in a Document

- packages/auth/lib/useragent.js
Before: `Republik App (1.0.1)`
After: `Republik App 1.0.1 / iOS 11.4.0 (iPhone)`
> feat(useragent): add os and device for republik app

- packages/auth/graphql/resolvers/_mutations/authorizeSession.js
- packages/auth/graphql/resolvers/_queries/unauthorizedSession.js
- packages/auth/graphql/schema-types.js
- packages/auth/graphql/schema.js
- packages/auth/lib/Fields.js
- packages/auth/lib/Users.js
- servers/publikator/script/db-migrate-all.js
This Pull Request provides information on additional fields required to authorize a session not unlike `requiredConsents` field.
Query `unauthorizedSession` first:
```gql
{ unauthorizedSession(
email: ...
token: ...
) {
requiredFields
} }
```
This query will result in something as follows:
```gql
{
"data": {
"unauthorizedSession": {
"requiredFields": [
"firstName",
"lastName"
]
}
}
}
```
Authorize a session with additional required fields like so:
```gql
mutation {
authorizeSession(
email: ...
tokens: ...,
...
fields: {
firstName: "Peter"
lastName: "Parker"
}
)
}
```
It requires UI to updated https://github.com/orbiting/republik-frontend/pull/183
> feat(auth): Query and submit additional fields when authorizing a session

- packages/base/express/graphql.js
- packages/base/package.json
A workaround for https://github.com/orbiting/app/issues/159
Handles all data coming from GraphQL—Publikator and user generated content.
Interception response bodies with express is hard and can easily lead to content length header problems. `apollo-server` does not offer a response hook out of the box but `apollo-server-express` is a thin wrapper which gets the json nicely as a string and is responsible to set the content length. It seemed like the safest and easiest solution to copy that wrapper and modify it.
> fix(encoding): strip \u2028 for iOS

- packages/election/graphql/resolvers/_mutations/createElection.js
- packages/election/graphql/resolvers/_mutations/submitCandidacy.js
- packages/election/graphql/schema-types.js
- packages/election/lib/db.js
- packages/election/migrations/sqls/20180912181821-election-up.sql
This Pull Request will send a candidacy confirmation email when submitting a candidacy for the first time.
Introduced an additional field to `elections` table: `shortSlug`.
It appears that election mails are surprisingly non-generic thus will get their own mailing templates. Template names are glued with regular template name and appends `_{shortSlug}` to it. It will use a "default" template without that slug. (Not using `elections.slug` or `id` as those strings are too long for MailChimp template names.)
Altered _lib/db.js_ to return `{ entity, isNew }` instead of `entity` only. Allows to understand if an entity was added or updated. Also adopted already existing code.
> feat(election): Send candidacy confirmation email

- packages/search/lib/indices/comments.js
- packages/search/script/inserts/comment.js
- servers/republik/graphql/resolvers/User.js
- servers/republik/graphql/resolvers/_queries/discussions.js
- servers/republik/migrations/20180928092218-hidden-discussion.js
- servers/republik/migrations/sqls/20180928092218-hidden-discussion-down.sql
- servers/republik/migrations/sqls/20180928092218-hidden-discussion-up.sql
This Pull Request allows to hide discussions and comments by setting `discussions.hidden = true` in database.
- It won't hide discussions when queried for a specific ID. 
- It will return comments if hidden discussions if queried specifically.
- iIt prevents indexing comments of hidden discussions into search database.
> feat(republik): Hide a discussion

- packages/documents/lib/meta.js
This ensures `meta.credits` is populated with (pre-)indexed document data.
To improve `search` query speed, some queries [are fired to retrieve documents without `doc.content.children`](https://github.com/orbiting/backends/blob/master/packages/search/graphql/resolvers/_queries/search.js#L350-L357).
packages/documents/lib/meta.js hereafter extracted credits [from non-existant `doc.content.children`](https://github.com/orbiting/backends/compare/fix-documents-meta-credits?expand=1#diff-6913b048f1a657df99bb40440fa3bdeeL16), and returned an empty array `credits` prop.
However, a document in ElasticSearch is stored with `doc.content.meta.credits` "pre-resolved" on publish and can be used.
It is a regression probably introduced back on June 26, 2018.
```gql
{
search(filter: {type: Document}) { …
```
> fix(documents): Retrieve meta.credits properly

- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/graphql/resolvers/_mutations/unpublish.js
- servers/publikator/lib/publicationScheduler.js
This Pull Requests extends repo search cache upserts for
- scheduled publications and pre-publications
- on `unpublish`
- on `publish`
> publikator: Repo search cache upserts

- packages/access/graphql/resolvers/User.js
- packages/access/graphql/schema-types.js
- packages/access/lib/campaigns.js
- packages/access/lib/grants.js
- packages/access/lib/mail.js
- servers/republik/modules/crowdfundings/lib/Mail.js
This Pull Request allows users with privileged roles, namely supporter and admin, to query campaigns and grants in the past.
> feat(access): Get past campaigns, grants (admin only)

- packages/access/lib/accessScheduler.js
- packages/access/lib/campaigns.js
- packages/access/lib/events.js
- packages/access/lib/grants.js
- packages/access/lib/mail.js
- packages/access/lib/memberships.js
- packages/access/migrations/20181001150848-followup.js
- packages/access/migrations/sqls/20181001150848-followup-down.sql
- packages/access/migrations/sqls/20181001150848-followup-up.sql
- servers/republik/lib/translations.json
- servers/republik/server.js
This Pull Request adds missing pieces to granting access feature:
- send a transactional email at the moment a grant expires
- send a transactional email to follow-up some time later (set in campaign itself)
Other changes include:
- Handle errors in `accessScheduler` more gracefully. Mandrill API proves to be not a reliable and throws frequently 500 HTTP Status Code errors containing not parseable content.
- Includes more verbose debug logging to understand who queried what and when.
- Changed schedulers interval to 10 minutes as matching happens upon sign in.
> feat(access): Send expiration and follow up transactional email

- servers/publikator/graphql/resolvers/Commit.js
GitHub GraphlQL-API truncated text after 500kb, the exact limit is not documented but an `isTruncated` flag is provided: https://developer.github.com/v4/object/blob/
This uses the rest API, which has a documented limit of 100mb:
https://developer.github.com/v3/git/blobs/
Perf:
`gql` with text: 1500 – 1700ms  
`gql` without text: 480 – 630ms  
`rest` 2000 – 2100ms
I'd always do `gql` & `rest`, as implemented now. Adds ~1s to all (uncached) commit fetching. Other option would add 2s to documents over 500kb and no delay to regular. But since mostly large documents (aka magazin) have perf issue I'd prefer adding 1s to all.
> fix(Commit): handle article.md bigger than 500kb

- packages/documents/lib/meta.js
This Pull Request rewrites changes made in https://github.com/orbiting/backends/pull/103. I only came hereafter to understand concept of `doc.meta.credits` and `doc.content` and credit nodes.
There are two paths retrieving credits for documents:
- via `doc.content` and retrieving (visiting) meta children (Publikator and Search, default path) 
- Search may sometimes not provide (`doc.content`) due to performance considerations. In that case we attempt to retrieve credits via `doc.meta` (data stored in ElasticSearch).
Latter is currently the case when using search in frontend.
> fix(documents): Retrieve credits in a more appropriate manner

- packages/voting/graphql/resolvers/Election.js
- packages/voting/graphql/resolvers/_queries/election.js
- packages/voting/graphql/resolvers/_queries/elections.js
- packages/voting/graphql/resolvers/_queries/voting.js
- packages/voting/graphql/resolvers/_queries/votings.js
- packages/voting/graphql/schema-types.js
- packages/voting/lib/queries.js
no access to year of birth or city for non associates – loosening the schema.
Changes
- remove role check on queries
- allow `city` and `yearOfBirth` to be null
- fix `userSubmitDate`: return date or null
> feat(voting): allow read access to votings and elections

- servers/republik/graphql/resolvers/Comment.js
According to the schema preview can be null but `Preview.string` not:
https://github.com/orbiting/backends/blob/ad8170c7899a071f7da6cb9af15b9cdc781dea0c/servers/republik/graphql/schema-types.js#L304-L307
https://github.com/orbiting/backends/blob/ad8170c7899a071f7da6cb9af15b9cdc781dea0c/servers/republik/graphql/schema-types.js#L323-L326
The current implementation explodes with unpublished text with `Cannot return null for non-nullable field Preview.string`.
However it looks like `preview` might be called somewhere else, for notifications?, too but I couldn't find it to verify if that can handle null instead of `{text: null: more: false}` (which is not gql schema compliant). Alt would be to return `{text: '', more: false}`.
> fix(Discussion): comment preview for unpublished comments

- packages/documents/graphql/resolvers/Document.js
`hasNextPage` is incorrectly `true` on initial front fetches without a `before`. This fixes this.
See `hasNextPage` on line 99, unchanged but now with a correct `lastIndex`.
> fix(documents): child pagination off by one

- packages/search/lib/Documents.js
Following values are in `meta.series`:
```
https://github.com/republik-dev/article-daniels-serienmaster
https://github.com/republik-dev/article-master
https://github.com/republik-dev/article-master
https://github.com/republik/article-intro
```
after passing through `getRepoId` `"https://github.com/republik/article-intro"` becomes `null` because it's not a recognized id (different org).
Querying for "meta.repoId: ["...", null]" leads to an elastic parse error:
```
[parsing_exception] No value specified for terms query, with { line=1 & col=199 }
```
> fix(series): sanitize repo ids before querying

- packages/voting/graphql/resolvers/QuestionTypeChoice.js
- packages/voting/graphql/resolvers/QuestionTypeDocument.js
- packages/voting/graphql/schema-types.js
- packages/voting/lib/Question/Choice.js
- packages/voting/lib/Question/Document.js
- packages/voting/lib/Question/Range.js
Add min count argument for choices and documents. Fix extra bucket for max value.
*Histogram Before*
```json
[
{
"count": 8,
"x0": -1,
"x1": -0.9
},
{
"count": 3,
"x0": -0.9,
"x1": -0.8
},
...
{
"count": 276,
"x0": 0.8,
"x1": 0.9
},
{
"count": 704,
"x0": 0.9,
"x1": 1
},
{
"count": 0,
"x0": 1,
"x1": 1
}
]
```
*After*
```json
[
{
"x0": -1,
"x1": -0.9,
"count": 4
},
{
"x0": -0.9,
"x1": -0.8,
"count": 2
},
...
{
"x0": 0.8,
"x1": 0.9,
"count": 176
},
{
"x0": 0.9,
"x1": 1,
"count": 459
}
]
```
> Improve Q Results

- servers/republik/modules/crowdfundings/lib/Mail.js
- servers/republik/modules/crowdfundings/lib/generateMemberships.js
This Pull Request fixes faulty auto-cancellation. Before this fix we did cancel a `MONTHLY_ABO` membership whenever a `ABO` membershipType was available, hence also for `ABO_GIVE` packages. Code ensures only certain packages can cause an auto-cancellation: `ABO` and `BENEFACTOR`.
It also fixes an error when `payment` entity was not available while attempt to send a pledge confirmation email. It failed to send pledge confirmation as a merge variable accessed `payment.method`. Error occurred when users paid via Stripe, and caused a subscription (`MONTHLY_ABO`) where a payment is not instantly available but added upon a Stripe web hook response. Before pledge confirmations were only sent on hook triggers e.g. a login.
> Fix auto cancel MONTHLY_ABO, and pledge confirmation email for subscriptions

- packages/mail/lib/sendMailTemplate.js
- servers/republik/modules/crowdfundings/lib/Mail.js
This Pull Request fixes two bugs:
- Won't use `mail.createMail` wrapper when sending pledge confirmation emails. In fact unnecessary. Bug due to overwritten context when using fn `sendMailTemplate`.
```
error in payPledge after transactionCommit Error: missing input
at send (backends/packages/mail/lib/mailLog.js:56:11)
at module.exports (backends/packages/mail/lib/sendMailTemplate.js:69:10)
at Object.sendMailTemplate (backends/packages/mail/NewsletterSubscription.js:45:20)
at Promise.all.pledges.map (backends/servers/republik/modules/crowdfundings/lib/Mail.js:295:17)
```
- Spreading into array when `mail.globalMergeVars` is undefined failed. Fixed.
```
(node:65) UnhandledPromiseRejectionWarning: TypeError: mail.globalMergeVars is not iterable
at module.exports …
```
> Fixes bugs when sending mail templates

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/Documents.js
- packages/search/lib/indices/documents.js
- servers/publikator/graphql/resolvers/_mutations/publish.js
This Pull Request changes publikator publish mutation.
It now gathers related document versions which are published or scheduled to be published, and ignores prepublished ones. This should only render "healthy" article URLs when pushing a newsletter to MailChimp.
If a document is prepublished, it will include prepublished related document versions.
> Ignore prepublished document version on publish

- .env.example
- package.json
- packages/github/lib/clients.js
- packages/github/package.json
- yarn.lock
This Pull Request limits amount of requests to Github GraphQL.
- No more than 1 concurrent connection
- Wait minimum 200ms before querying again
Uses NPM package [bottleneck](https://www.npmjs.com/package/bottleneck) as a generic job queue. Would allow clustering via Redis.
> feat(github): Enable optional GitHub GraphQL API rate limit

- servers/republik/migrations/20190109074657-paymentslip-bank-accounts.js
- servers/republik/migrations/sqls/20190109074657-paymentslip-bank-accounts-down.sql
- servers/republik/migrations/sqls/20190109074657-paymentslip-bank-accounts-up.sql
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/importPostfinanceCSV.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_queries/postfinancePayments.js
- servers/republik/modules/crowdfundings/graphql/schema-types.js
This Pull Request creates table `bankAccounts` with an `iban` and `label` prop. It then attempts to recognize in uploaded PostFinance payment files to which account import belongs to and will link them in `postfinancePayments`.
It does not (yet) validate if payment was expected on a bank account.
> Link PostFinance payments to receiving bank account

- packages/documents/lib/meta.js
- servers/republik/.env.example
This Pull Request allows suppressing evaluation of `Document.meta.estimatedReadingMinutes` with environment variable `SUPPRESS_READING_MINUTES`, which is parsed on startup. Requires a JSON object.
Example:
```
SUPPRESS_READING_MINUTES='{"series":["An der Bar"]}'
```
> feat(documents): Evaluate SUPRESS_READING_MINUTES config

- packages/schedulers/lib/intervalScheduler.js
- packages/schedulers/lib/timeScheduler.js
- servers/republik/modules/crowdfundings/graphql/schema-types.js
- servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
- servers/republik/modules/crowdfundings/lib/scheduler/changeover.js
- servers/republik/modules/crowdfundings/lib/scheduler/deactivate.js
- servers/republik/modules/crowdfundings/lib/scheduler/index.js
This Pull Request primarily adds to membership schedulers:
* `changeover` to find expired memberships which can be replace with a dormant membership
* `deactivate` to deactivate memberships
`changeover` checks users with active memberships after their latest membership period if there are dormant memberships to activate. If so, it elects one, deactivates old membership and activates dormant membership.
`deactivate` will deactivate cancelled memberships after latest membership period ended, and, for the "grace period", it will deactivate uncancelled memberships 14 days after latest membership period ended.
To avoid user confusion it deactivates memberships after the end of a day a period ends. (Period might end on 2019-01-16 at 3pm. Scheduler won't deactivate membership before 2019-01-16 …
> Schedulers to changeover or deactivate memberships

- packages/auth/lib/Fields.js
This Pull Request aligns requirements to rest of backends which require only at least one non-space char for first and last name.
> fix(auth): Check name fields length, require only single non-space char

- app.json
- servers/republik/graphql/schema-types.js
- servers/republik/modules/crowdfundings/lib/Mail.js
It looks like removing `FEUILLETON` from the `NewsletterName` enum shouldn't hurt us for existing subscriptions, because it's only used on `updateNewsletterSubscription` and not on getting a `NewsletterSubscription`. (Will test on staging of course.)
> fix(newsletters): remove feuilleton newsletter

- servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
This Pull Request makes sure that a deactivated membership can be prolonged unless there is an active membership.
> fix(crowdfundings): Prevent prolonging of deactivated memberships

- servers/republik/modules/crowdfundings/graphql/resolvers/User.js
- servers/republik/modules/crowdfundings/lib/CustomPackages/rules/earlyAdopterBonus.js
- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
This Pull Request introduces multiple changes:
* Feature: Return `prolongBeforeDate` on **pending pledges too** if `periods.max(endDate)` is smaller than `now`
* Fix: Check if earlyAdopterBonus days is **a positive value**
* Fix: Lower minEndDate for T-0 email
> prolongBeforeDate on pending pledges and fixes

- servers/republik/modules/crowdfundings/lib/generateMemberships.js
This Pull Request will not generate periods on a membership if pledge passed has already generate periods. It makes `generateMemberships` somewhat idempotent.
> fix(crowdfundings): Do not generate periods if generated already

- servers/republik/modules/crowdfundings/lib/CustomPackages/rules/earlyAdopterBonus.js
Mutate `bonus` later to prevent single-day-bonus.
> fix(crowdfundings): Prevent single day bonus

- servers/republik/modules/crowdfundings/graphql/resolvers/Membership.js
- servers/republik/modules/crowdfundings/graphql/resolvers/User.js
- servers/republik/modules/crowdfundings/graphql/schema-types.js
- servers/republik/modules/crowdfundings/lib/User.js
- servers/republik/modules/crowdfundings/lib/cache.js
This Pull Requests adds props to `Membership` types:
* `needsProlong: Boolean!`, flag whether membership can be prolonged
* `endDate: DateTime`, date time describing when a membership ends
* `graceEndDate: DateTime`, date time describing when a membership is deactivated
It further returns an active membership on `User.activeMembership`.
Some resolver results are cached up to 24h and invalidate upon some membership mutations.
- `User.activeMembership`, membership query
- `Membership.type`, type query
- `Membership.needsProlong`
- `Membership.endDate`
- `Membership.graceEndDate`
Sample GraphQL Query:
```gql
{
me {
activeMembership {
needsProlong
endDate
graceEndDate
type {
name
}
}
}
}
```
> Extend Membership type

- packages/access/lib/grants.js
- packages/utils/__tests__/applyPgInterval.test.js
- packages/utils/applyPgInterval.js
- packages/utils/package.json
- servers/republik/modules/crowdfundings/graphql/resolvers/Membership.js
- servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
- yarn.lock
pogi uses [postgres-interval](https://www.npmjs.com/package/postgres-interval) to represent intervals stored in Postgres database (via pg-core).
New util `applyPgInterval` in utils package is either adding or subtracting such an interval on a given date.
This Pull Request refactors code parts which did already added a Postgres interval to dates.
> Create util to apply a PostgresInterval object and refactor

- packages/utils/__tests__/applyPgInterval.test.js
- packages/utils/applyPgInterval.js
Objects provided in `interval` arguments may not be of type `PostgresInterval` (e.g. parsed cache object). If their similar to a `PostgresInterval` object, accept them anyway.
Fixes #206
> fix(utils): Accept object similar to PostgresInterval

- .env.example
- .travis.yml
- packages/auth/README.md
- packages/auth/lib/Users.js
AUTO_LOGIN_REGEX signs in matching emails automatically after 2 seconds.
Set `AUTO_LOGIN_REGEX=^([a-zA-Z0-9._%+-]+)@republik\.ch$` for a more open life in development.
- fix auto `authorizeSession`
- rename AUTO_LOGIN -> AUTO_LOGIN_REGEX
> fix auto login, AUTO_LOGIN -> AUTO_LOGIN_REGEX

- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/cancelPledge.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/claimMembership.js
- servers/republik/modules/crowdfundings/lib/generateMemberships.js
Provide context `mail` in `cancelMembership` calls and move suppress-flags to `details` in function argument call.
> Fix some cancelMembership calls

- servers/republik/modules/crowdfundings/graphql/resolvers/_queries/adminUsers.js
This Pull Request attempts to improve search results on `adminUsers` GraphQL query.
It only changes how database is queried, and what results are returned in which order. It does not improve speed (neither does it decrease it).
**More relevant results**
Query changes relay even more on word similarity and distance calculated by Postgres ("relevance"). The more relevant a term is in on-the-fly generated searchable text (`concat_ws(...)` parts), the further up result should appear.
Results are not shown if their relevance is deemed too low.
There are two thresholds we can adjust: `WORD_SIMILARITY_THRESHOLD` ("similiarity") and `WORD_DISTANCE_THRESHOLD` ("distance"). Results with a similarity ratio below 0.6 are omitted, as well as results whith a distance ratio above 0.5.
Thresholds were …
>  feat(crowdfundings): Improve adminUsers search results 

- servers/republik/modules/crowdfundings/graphql/resolvers/Pledge.js
Querying for `User.pleges.payments` returns payments sorted by `Payment.createdAt` in a descending manner.
```
{
me {
pledges {
payments {
createdAt
}
}
}
}
```
Fixes https://github.com/orbiting/republik-admin-frontend/issues/25
> fix(crowdfundings): Return Pledge.payments by Payment.createdAt desc

- packages/crowdsourcing/graphql/resolvers/_mutations/submitInheritanceStory.js
- packages/mail/lib/mailLog.js
- packages/mail/lib/sendMailTemplate.js
Allows to disable logging a message in `mailLog` table. Disabled logging in mutation `submitInheritenceStory`.
It adds a templates name as a tag for more convenience in Mandrill dashboard.
> feat(mail): Flag to toggle message logging itself

- servers/republik/modules/crowdfundings/lib/Mail.js
This prevents sending confirmation email when a pledge was cancelled.
A previously unverified user account containing a meanwhile cancelled pledge received a pledge conformation email 8 months later upon claiming an access grant, effectively verifying the account and triggering sending of pending pledge confirmation emails.
> fix(crowdfundings): Exclude cancelled pledges

- packages/access/graphql/schema-types.js
- packages/access/lib/campaigns.js
- packages/access/lib/constraints/requireExistingGrants.js
- packages/access/lib/grants.js
- packages/access/script/generateVoucherCodes.js
Can generate a series of grants for a user with only voucher codes in campaign. Prefix and amount can be specified, too.
This Pull Request also adds a constraint which requires existing grants to display a campaign. User should only see campaign if grants are in campaign. Grants may be pre-generated e.g. a series
of voucher codes which may be printed on business cards.
Fixes constraint's default `payload`: Allows to create campaigns without any constraints having to generate `payload.slots = {...}`. Previously, schema allowed `Campaign.slots` to be null.
**How to test**
Create a dedicated campaign, using new constraint:
```sql
INSERT INTO "public"."accessCampaigns"("id","title","description","grantPeriodInterval","emailFollowup","beginAt","endAt","constraints","createdAt","updatedAt","gran …
```
> feat(access): Add script to generate voucher codes in bulk 

- packages/search/script/inserts/repo.js
- servers/publikator/graphql/resolvers/Repo.js
- servers/publikator/graphql/resolvers/_mutations/archive.js
- servers/publikator/graphql/schema-types.js
- servers/publikator/graphql/schema.js
- servers/publikator/lib/cache/upsert.js
- servers/publikator/lib/github/index.js
- servers/publikator/lib/translations.json
Sets `archived` flag on repositories provided and updates `repo` cache in ElasticSearch.
If a repository has tags indicated an article is published, it fails. An additional flag (`unpublish`) will unpublish such articles first.
> feat(publikator): Add mutation to archive repo

- packages/assets/lib/returnImage.js
- packages/assets/package.json
- yarn.lock
use file-type-stream2 to better detect mime. E.g. `file-type-stream` was not able to detect `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` with v2 that works perfectly, due to the updated `file-type` dependency and reading more of the stream to detect the type.
> fix(assets): improve mime detection

- packages/assets/lib/webp.js
- packages/documents/graphql/resolvers/Document.js
- packages/documents/graphql/resolvers/_queries/document.js
- packages/documents/graphql/resolvers/_queries/documents.js
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/Documents.js
only load linked docs in returned content or children
This speeds up getting the front document a lot. Locally the response time goes from ~140ms to ~70ms (both with hot caches) with the smaller dev documents collection. In prd the gains may reach 5x to 10x. I expect the current prd ~700ms to go down to ~200ms.
~ToDo~:
- ~new `afterDate` & `beforeDate` query for `Document.children` for overview page~
Decided not to implement advanced children filtering in backend (credit line based) and instead hard code some teaser ids in the frontend: https://github.com/orbiting/republik-frontend/commit/7bdab34cc56717c146003fdc5f75e16c3285dd58#diff-048df1fa60145e7b472e7ed8cafbcf72R37
This will allow for the same optimisations.
> feat(documents): optimise linked/related docs loading

- servers/republik/graphql/resolvers/_queries/employees.js
- servers/republik/graphql/schema.js
New argument for `employees` to shuffle and limit the result to the specified count
- one famous female and one famous male is boosted
- ensures unique users
> feat(employees): shuffle and boost

- packages/migrations/migrations/20190701024155-group-votings.js
- packages/voting/graphql/resolvers/Voting.js
- packages/voting/graphql/resolvers/VotingTurnout.js
- packages/voting/graphql/resolvers/_mutations/createVoting.js
- packages/voting/graphql/schema-types.js
- packages/voting/lib/Voting.js
- packages/voting/lib/queries.js
- packages/voting/migrations/sqls/20190701024155-group-votings-down.sql
- packages/voting/migrations/sqls/20190701024155-group-votings-up.sql
group votings by setting `groupSlug: 'aslug'` when creating votings and retrieve the same `groupTurnout` on each member.
`groupTurnout.submitted` num unique users which have submitted in at least one of the groups votings.
`groupTurnout.eligible` is the same as turnout.eligible
For query examples check the [PR for july 2019 votings](https://github.com/orbiting/republik-frontend/pull/312)
> feat(voting): groupTurnout

- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
This Pull Request fixes bug when sending membership owner prolong notices. It prevent sending those notices.
Bug was introduced while [refactoring database connections](https://github.com/orbiting/backends/pull/224): [User.getProlongBeforeDate](https://github.com/orbiting/backends/blob/0d936dbcb3a5e9239cde85359e96175856bfdf13/servers/republik/modules/crowdfundings/graphql/resolvers/User.js#L80) now requires a context including a redis instance to [create a cache instance](https://github.com/orbiting/backends/blob/0d936dbcb3a5e9239cde85359e96175856bfdf13/servers/republik/modules/crowdfundings/graphql/resolvers/User.js#L86-L90).
It temporary prevents T-0 mails to be send.
> fix(crowdfundings): Sending prolong notices

- packages/collections/lib/Collection.js
[If `data.percentage` was `undefined` it still determined `accessor` to be "percentage"](0e63502). This hindered `data.max` evaluation for media items w/ `data.secs` but no percentage.
This Pull Request includes also some refactoring:
- Uses `newData` variable in condition instead of `data`
- Removes unnecessary `else` branch
> fix(collections): Determines accessor properly

- packages/auth/lib/challenges/EmailCodeChallenge.js
This Pull Request splits an email code onto chunks of 3 chars and glues those chunks with a space. A chunked code helps a user to remember it.
Excerpt from transactional email hereafter:
> fix(auth): Split challenge payload into chunks

- servers/republik/graphql/resolvers/_queries/employees.js
- servers/republik/graphql/schema-types.js
- servers/republik/graphql/schema.js
Allows to set `withGreeting` and `withFamous` arguments on `employees` query.
Relates to https://github.com/orbiting/republik-frontend/pull/335
> feat(republik): Return Employee.greeting

- packages/access/lib/grants.js
- packages/access/lib/mail.js
- packages/access/migrations/sqls/20190909040718-mail-config-down.sql
- packages/access/migrations/sqls/20190909040718-mail-config-up.sql
- packages/migrations/migrations/20190909040718-mail-config.js
This Pull Request adds an attribute to `accessCampaigns`, named `config`. It allows to configure a campaign with props. Implemented are these props:
- `emails`
- `subscribeToEditorialNewsletters`
`emails` is an array containing objects, each dedicated to configure an email template to suit campaign needs.
```json
{
"emails": [
{
"party": "recipient",
"enabled": false,
"template": "invitation"
}
]
}
```
Above configuration would disable onboarding email to recipient.
`subscribeToEditorialNewsletters` is a boolean value, and if set to `true` users will be subscribed to editorial newsletters.
```json
{
"subscribeToEditorialNewsletters": false
}
```
Above configuration would not "force" subscribe to editorial newsletters.
> feat(access): Add email config per campaign and check for disabled emails

- packages/cards/migrations/sqls/20190911012939-improvements-down.sql
- packages/cards/migrations/sqls/20190911012939-improvements-up.sql
- packages/cards/script/insert-discussions.js
- packages/discussions/graphql/resolvers/Comment.js
- packages/discussions/graphql/resolvers/_queries/comments.js
- packages/discussions/loaders/Comment.js
- packages/discussions/loaders/Discussion.js
- packages/migrations/migrations/20190911012939-improvements.js
* Alter hidden flag behaviour, preventing hidden discussions to appear in `comments` query
* Load `Comment.comments` even if data is not propagated and return accuracte counts
* Insert and link discussions for `CardGroup` entities (script)
* Rename field to remove typo disucussionId/discussionId
> Hide discussions and return accurate Comment.comments counts

- packages/cards/graphql/resolvers/CardGroup.js
- packages/cards/graphql/resolvers/User.js
- packages/cards/graphql/resolvers/_queries/cards.js
- packages/cards/graphql/schema-types.js
- packages/cards/graphql/schema.js
- packages/cards/lib/cards.js
Queries with `CardConnection` as results accept filters, namely `CardFiltersInput`.
Example:
```gql
{
cards(filters: {parties: ["SVP", "BDP"]}) {
nodes {
payload(paths: ["party"])
}
}
}
```
> feat(cards): Add filters for parties and cards a user is subscribed to

- packages/cards/graphql/resolvers/CardAggregation.js
- packages/cards/graphql/resolvers/CardAggregationBucket.js
- packages/cards/graphql/resolvers/CardConnection.js
- packages/cards/graphql/schema-types.js
- packages/cards/lib/cards.js
- packages/utils/paginate.js
This puts `CardConnection.aggregations` at our disposal and returns aggregations with "buckets".
Usage example:
```gql
{
cards {
totalCount
aggregations(keys: [fraction]) {
key
buckets {
value
cards {
totalCount
}
}
}
}
}
```
Results in
```json
{
"data": {
"cards": {
"totalCount": 4741,
"aggregations": [
{
"key": "fraction",
"buckets": [
{
"value": "FDP",
"cards": {
"totalCount": 537
}
},
[...]
]
}
]
}
}
}
```
> feat(cards): Add CardConnection.aggregations at our disposal

- packages/auth/graphql/resolvers/_queries/echo.js
- packages/auth/graphql/schema-types.js
- packages/auth/lib/Users.js
- packages/auth/lib/useragent.js
When signing in in Republik app, default first factor (token, challenge) becomes `EMAIL_TOKEN`.
Can be overwritten if token type is explicitly stated.
And for fun, `echo` query returns `isApp` flag.
> feat(auth): Default auth challenge to EMAIL_TOKEN if RepublikApp user agent is detected

- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
These users will slip into a dedicated, yet-to-be-defined flow.
> feat(crowdfundings): Exclude membership with auto pay flag from prolong notices flow

- packages/mail/lib/sendMailTemplate.js
- packages/mail/templates/membership_owner_autopay_notice_5.html
- packages/translate/translations.json
- packages/utils/findLastMembershipPledge.js
- packages/utils/index.js
- servers/republik/modules/crowdfundings/lib/Mail.js
- servers/republik/modules/crowdfundings/lib/scheduler/index.js
- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
This Pull Request sends earliest 5 days before a membership is planned to be renewed a transactional email, notify a user about upcoming charge.
Code is run [in membership owner scheduler](https://github.com/orbiting/backends/compare/feat-autopay-notice-5?expand=1#diff-7fd8e0d8a72be494c664c0b3c22c555d) in which we hold now a new bucket ("membership_owner_autopay_notice_5"), and altered scheduler to allow `autoPay` to be a bucket condition.
Membership owner scheduler [runs every 10 minutes](https://github.com/orbiting/backends/compare/feat-autopay-notice-5?expand=1#diff-588ec577936693da893ff2fc8d4b4424R43-R51) instead of once a day.
Upcoming charge is determined using [last membership pledge and it's (most recent) payment](https://github.com/orbiting/backends/compare/feat-autopay-notice-5?e …
> Notice email about automated charge to membership owners

- packages/mail/templates/payment_successful_abo.html
- packages/mail/templates/payment_successful_abo_give.html
- packages/mail/templates/payment_successful_abo_give_months.html
- packages/mail/templates/payment_successful_benefactor.html
- packages/mail/templates/payment_successful_prolong.html
- packages/mail/templates/pledge_abo.html
- packages/mail/templates/pledge_abo_give.html
- packages/mail/templates/pledge_abo_give_months.html
- packages/mail/templates/pledge_benefactor.html
- packages/mail/templates/pledge_prolong.html
- packages/translate/translations.json
- servers/republik/modules/crowdfundings/graphql/resolvers/Pledge.js
- servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
- servers/republik/modules/crowdfundings/lib/Mail.js
Also sorting of options in `lib/CustomPackages`, `lib/Mail` and `Pledge.options` resolver got improved.
This Pull Request should enable us to list package options other than memberships in `User.customPackages` as well as validated and accept them when submitting a pledge.
> feat(crowdfundings): Return reward types other than MembershipType in custom package options

- packages/schedulers/lib/intervalScheduler.js
- packages/schedulers/lib/timeScheduler.js
- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/graphql/resolvers/_mutations/unpublish.js
- servers/publikator/lib/PublicationScheduler.js
This Pull Request replaces current publication scheduler to become more robust.
It uses an interval scheduler and runs every 10 seconds. This resolves some long-standing issues in case an error is thrown while publishing or scheduling next run: A short interval ensures quick recovery on temporary issues and interval scheduled is more error prone. Publication scheduler contains a little less code to maintain.
There were no code changes to publishing procedure itself.
> Replace time scheduled w/ interval publication scheduler

- packages/mail/templates/subscription_end.html
- servers/republik/modules/crowdfundings/lib/payments/stripe/webhooks/customerSubscription.js
- servers/republik/modules/crowdfundings/lib/payments/stripe/webhooks/invoicePaymentFailed.js
This Pull Request prevents two transactional emails to be send back-to-back:
a) last failed charge attempt ("payment failed")
b) subscription now ending.
If a payment fails, Stripe reports event `invoice.payment_failed` and a transactional email is sent (a).
Subsequently, if there are no more attempts to be scheduled, subscription will be deleted. Stripe then reports `customer.subscription.deleted`. Once more a transactional email (b) is dispatched, usually within moments of previous event `invoice.payment_failed`.
Event `invoice.payment_failed` holds a property `data.object.next_payment_attempt` and is falsy, if there is no more charge attempt scheduled. In this code change, we use this property to suppress "payment failed" email (a).
Meanwhile "subscription end" email (b) has a new …
> fix(crowdfundings): Send subscription_failed mail only of there is a next payment attempt scheduled

- packages/migrations/migrations/20191203081148-hide-package-options.js
- servers/republik/migrations/sqls/20191203081148-hide-package-options-down.sql
- servers/republik/migrations/sqls/20191203081148-hide-package-options-up.sql
- servers/republik/modules/crowdfundings/graphql/resolvers/Crowdfunding.js
- servers/republik/modules/crowdfundings/graphql/resolvers/Package.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/submitPledge.js
- servers/republik/modules/crowdfundings/lib/CustomPackages/index.js
- servers/republik/modules/crowdfundings/lib/User.js
This Pull Request allows to gracefully "phase-out" `packageOptions`. Each option hold two new attributes:
- `hiddenAt`: Once set, package option is no longer returned after a specific date
- `disabledAt`: Once set, creating pledges with package option will fail it after a specific date (
If all package options are hidden, package is no longer returned. This applies to queries `me.customPackages[]` and `crowdfunding.packages[].options[]`.
(Boolean attribute `disabled` is removed in a subsequent Pull Request: https://github.com/orbiting/backends/pull/344)
Changes include:
* Add fields to packageOptions table
* Alter custom package code to hide disabled, hidden options
* Move Package.options query to Crowdfunding.packages
* Change Crowdfunding.packages resolver to respect hiddenAt, …
> feat(republik): Add hiddenAt, disabledAt attributes and respect in queries, mutations

- packages/discussions/graphql/resolvers/Discussion/comments.js
fixes discussion.comments queries with `maxDepth` and `first`.
More comments than `first` might be returned if the `first` comments based on `orderBy` are depth > 0, but that's nothing new.
example query: https://api.republik.ch/graphiql/?query=%7B%0A%20%20discussion(id%3A%20%221a521e44-7f88-44bf-bb87-a582e30a0fba%22)%20%7B%0A%20%20%20%20title%0A%20%20%20%20comments(first%3A%203%2C%20orderBy%3A%20DATE%2C%20orderDirection%3A%20DESC)%20%7B%0A%20%20%20%20%20%20totalCount%0A%20%20%20%20%20%20directTotalCount%0A%20%20%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20%20%20depth%0A%20%20%20%20%20%20%20%20hotness%0A%20%20%20%20%20%20%20%20createdAt%0A%20%20%20%20%20%20%20%20updatedAt%0A%20%20%20%20%20%20%20%20adminUnpublished%0A%20%20%20%20%20%20%20%20preview(length%3A%20240)%20%7B%0A%20%20%20%20%20%20 …
> fix(discussion): respect maxDepth of first comments

- packages/base/lib/Redis.js
- packages/search/lib/cache.js
- servers/republik/modules/crowdfundings/lib/cache.js
Scans trough a key pattern and applies `async mapFn(client, key)` to each key.
> feat(base): Add redis.scanMap helper function and replace EVAL calls

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/indices/documents.js
- servers/publikator/lib/Document.js
This should solve too little or no results when querying: `Urs Bruderer`, `Anna Miller`, `An der Bar`.
* feat: Stringify credits to `meta.creditsString` and queries them. `meta.authors` worked only if author names are linked, otherwise array is empty. This change replaces `meta.authors` w/ `meta.creditsString` and boosts it.
* fix(search): Query variations of terms. If there is no search operator used, this is the query pattern submitted: `term | "term" | term~` and resulting in expected, weighted results.
Requires reindexing documents.
> Improvements to querying and indexed data

- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/Documents.js
- packages/search/lib/indices/documents.js
- packages/search/lib/utils.js
This is a first attempt on weighting results – determined by `query` beforehand – to get a more "reasonable" relevance scoring.
Use function scoring to weight results
* Boost series, and long reads
* Deboost editorial newsletter slightly
Turns out length of an document is a good indicator whether should be ranked higher or not.
Also removes `HTML` identifier blocks in fn `mdastContentToString`.
> Improvements to result weighting

- .env.example
- packages/mail/MandrillInterface.js
- packages/mail/NodemailerInterface.js
- packages/mail/errors.js
- packages/mail/lib/sendMail.js
- packages/mail/lib/sendMailTemplate.js
- packages/mail/package.json
- yarn.lock
This Pull Request enables to use to send emails via [nodemailer](https://nodemailer.com/about/) instead of Mandrill: `NodemailerInterface`
`NodemailerInterface` also replaces simple handlebars variables.
To test, setup these ENV variables first, here including some examples.
```sh
SEND_MAILS_NODEMAILER_REGEX=^signin.*
SEND_MAILS_NODEMAILER_CONNECTION_URL='smtps://inbox@domain.tld:lengthy-password-with-dashes@asmtp.mail.hostpoint.ch/?pool=true'
```
Upcoming changes include:
- Allow to pause sending over either interface e. g. to pause Mandrill
- Script to resume paused emails
> feat(mail): Send some transactionals via nodemailer

- .env.example
- packages/mail/NodemailerInterface.js
- packages/mail/lib/sendMail.js
- packages/mail/lib/sendMailTemplate.js
- packages/mail/migrations/sqls/20200108103449-maillog-status-pending-down.sql
- packages/mail/migrations/sqls/20200108103449-maillog-status-pending-up.sql
- packages/mail/utils/sendResultNormalizer.js
- packages/mail/utils/shouldScheduleMessage.js
- packages/migrations/migrations/20200108103449-maillog-status-pending.js
This Pull Request can deem emails to be "scheduled" and be placed in `mailLog` as such.
ENV variable `SEND_MAILS_SCHEDULE_REGEX` accepts a regular expression and matches mail template names against it; if true, an email is scheduled instead of send.
Due to factors unbeknownst to us, we may need to hold off on sending emails but still have them queued. `mailLog` with records on status `SCHEDULED` just to that.
To test, setup ENV variable first, here including some examples.
```sh
SEND_MAILS_SCHEDULE_REGEX=^[^signin].*
```
Upcoming changes include:
- Script to sent previously scheduled emails
> feat(mail): Schedule some emails instead of sending them

- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/claimMembership.js
- servers/republik/modules/crowdfundings/lib/generateMemberships.js
When claiming a membership or upgrading, redis instance was not available and did throw error:
TypeError: Cannot read property 'scanMap' of undefined
> fix(crowdfundings): Provide redis instance to cancelMembership

- packages/mail/templates/membership_owner_autopay_failed.html
- packages/mail/templates/membership_owner_autopay_successful.html
- servers/republik/modules/crowdfundings/lib/Mail.js
- servers/republik/modules/crowdfundings/lib/scheduler/index.js
- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
- servers/republik/modules/crowdfundings/lib/scheduler/owners/charging.js
- Won't send emails if charge attempt was anything but `type: 'card_error'`. These errors will have to be checked manually.
- Auto-Pay related mail templates updated with a (temporary) apology
- Restore membership-owners scheduler, and limit amount of users looked at per run (`MEMBERSHIP_SCHEDULER_USER_LIMIT`)
> Autopay: Fallout

- packages/mail/templates/membership_owner_prolong_winback_7.html
- packages/translate/translations.json
- servers/republik/modules/crowdfundings/lib/scheduler/owners.js
- Template name: `membership_owner_prolong_winback_7` (mails before prolong date `membership_owner_prolong_notice_*`).
- Time windows: between 7 and 10 days after prolong date
> feat: Add T+7 template and bucket

- servers/republik/graphql/resolvers/MembershipStats/countRange.js
- servers/republik/graphql/resolvers/MembershipStats/evolution.js
- servers/republik/graphql/resolvers/RevenueStats/surplus.js
- servers/republik/graphql/schema-types.js
- servers/republik/modules/crowdfundings/lib/scheduler/index.js
quick and dirty solution to counter switch.
[count range query](http://api.republik.test/graphiql/?query=query%20StatusPage%20%7B%0A%20%20revenueStats%20%7B%0A%20%20%20%20surplus(min%3A%20%222019-11-30T23%3A00%3A00Z%22%20%20forceRecache%3A%20true)%20%7B%0A%20%20%20%20%20%20total%0A%20%20%20%20%20%20updatedAt%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20membershipStats%20%7B%0A%20%20%20%20count%0A%20%20%20%20countRange(min%3A%20%222020-02-29T23%3A00%3A00Z%22%20max%3A%20%222020-03-31T23%3A00%3A00Z%22)%20%0A%20%20%20%20evolution(min%3A%20%222019-12%22%2C%20max%3A%20%222020-03%22%20forceRecache%3A%20true)%20%7B%0A%20%20%20%20%20%20buckets%20%7B%0A%20%20%20%20%20%20%20%20key%0A%20%20%20%20%20%20%20%20gaining%0A%20%20%20%20%20%20%20%20ending%0A%20 …
> switch to counting all payments instead of surplus after 19000 memberships, fix surplus

- packages/documents/graphql/schema-types.js
usage: get it from formats directly and from formats of newsletters
```graphql
{
document(path: "/format/covid-19-uhr-newsletter") {
id
meta {
title
newsletter {
name
free
}
}
}
doc: document(path: "/2020/03/16/test-123") {
id
meta {
title
format {
id
meta {
title
newsletter {
name
free
}
}
}
}
}
}
```
> feat(documents): expose meta.newsletter

- packages/discussions/lib/Notifications.js
- packages/mail/templates/cf_comment_notification_new.html
- packages/mail/templates/cf_comment_notification_new.txt
Merge variable `CONTENT` contains HTML version of (markdown) `comment.content`. This is ill-suited for plain-text part of comment notification email.
This Pull Request converts HTML version to plain-text version and includes that one in plain-text part of comment notification email, similar to plain-text generation script.
Picking converting over simply `comment.content` as it respects padding and and link pattern.
> fix(mail): Send plain-text comment notification w/ plain-text content

- packages/scalars/graphql/resolvers/YearMonthDate.js
- packages/utils/cache.js
- packages/utils/index.js
- servers/republik/graphql/resolvers/MembershipStats/evolution.js
- servers/republik/lib/MembershipStats/evolution.js
- servers/republik/modules/crowdfundings/lib/scheduler/index.js
- servers/republik/script/MembershipStats/evolution/populate.js
This Pull Request refactors `MembershipStats.evolution`. It uses pre-populated data and returns specified monthly buckets (a date range).
Pre-populated data contains _all_ months and is populated either via scheduler or a script.
Pull Request drops "switchBucket" code parts.
**Script to populate data**
```
$ servers/republik/script/MembershipStats/evolution/populate.js
Begin...
Done.
```
It introduces a preliminary version of `cache` in package `utils`, an almost a blunt copy of servers/republik/modules/crowdfundings/lib/cache.js. If this proves successful, we may adopt it elswhere.
> refactor(republik): Use pre-populated data in MembershipStats.evolution

- packages/documents/lib/resolve.js
- packages/search/lib/Documents.js
- packages/subscriptions/graphql/resolvers/Document.js
- servers/publikator/graphql/resolvers/Meta.js
- servers/publikator/lib/Notifications.js
This Pull Requests changes return type of `getRepoId(url, requireQuery)`, and merges search parameters of repo URL with resolved document URL.
**Return type of `getRepoId(url, requireQuery)`**
Instead of a string, it returns an object with these props:
- `repoId`: set if repo ID is parseable
- `parsedUrl`: returns an `URL` object with parsed argument `url`
Changing return type here reduces `new URL` calls on same URL.
**Merge search parameters of repo URL with resolved document URL**
Keeps repo URL search parameters when resolving to a document URL.
_Example_
https://github.com/republik-dev/pae-article-zielartikel?autoSlug&foo=bar&audio=1#irgend-ein-hash
becomes
https://frontend.url/2022/02/22/web-slug?foo=bar&audio=1#irgend-ein-hash
> feat(documents): Merge repo URL search params before resolving document URL

- servers/republik/script/finance/calculateKpis.js
Changes should include `DONATE_POT` donations in «Spenden» and «Stornierte Spenden» for PROJECT_R company.
(It also removes unnecessary packageName filter for Mitgliedschaften, Stornierte Mitgliedschaften.)
> fix(republik): Adopt DONATE_POT package in script/finance/calculateKpis

- packages/auth/graphql/resolvers/User.js
- packages/auth/graphql/resolvers/_mutations/signIn.js
- packages/auth/graphql/schema-types.js
- packages/auth/graphql/schema.js
- packages/auth/lib/AccessToken.js
- packages/auth/lib/Users.js
- packages/auth/lib/challenges/AccessTokenChallenge.js
- packages/auth/lib/challenges/AuthorizeTokenChallenge.js
- packages/auth/lib/challenges/index.js
- packages/auth/migrations/sqls/20200415071450-token-type-authorize-down.sql
- packages/auth/migrations/sqls/20200415071450-token-type-authorize-up.sql
- packages/discussions/package.json
- packages/documents/package.json
- packages/migrations/migrations/20200415071450-token-type-authorize.js
- packages/translate/translations.json
- servers/republik/package.json
- yarn.lock
This Pull Request adds a new flow on how users can authorize a session.  It allows users to authorize with an access token, scoped to `AUTHORIZE_SESSION`.
**Access Token with `AUTHORIZE_SESSION` scope**
Access token can only be generated _by users_ with `admin` or `supporter` role via `AccessToken.issueForUser`, or _the system_ itself, for transactional emails via `AccessToken.generateForUser`.
This scoped access token …
- … is valid for 5 days
- … can be used 1 time as an "authorize" token
To enable us to generate more than a single token a day, it's hashed payload is fitted with an ISO 8601 timestamp down to milliseconds (instead of a date).
**Usage Flow**
1. Request `mutation { signIn(...) }` with email and access token.
A session is initialized, attempts to a) validated an access …
> feat(auth): Authorize w/ an AUTHORIZE_SESSION access token

- packages/maillog/graphql/resolvers/MailLogRecord.js
- packages/maillog/graphql/resolvers/User.js
- packages/maillog/graphql/resolvers/_queries/mailLog.js
- packages/maillog/graphql/schema-types.js
- packages/maillog/graphql/schema.js
- packages/maillog/lib/paginate.js
- packages/maillog/lib/record.js
This Pull Request adds `filters: { errornous: TRUE|FALSE }` to mail log queries.
```gql
{
mailLog(filters: {errornous: true}) {
totalCount
nodes {
email
error
}
}
me {
mailLog(filters: {errornous: false}) {
totalCount
nodes {
error
}
}
}
}
```
Code is slightly refactored and extended, moving pagination (including filtering) into a lib-file as well as record props conditionals (error, status, template).
> feat(maillog): Add errornous record filter for mail log records

- packages/mail/MailchimpInterface.js
- packages/mail/lib/index.js
- packages/mail/lib/operations/covidAccessTokens.js
- packages/mail/lib/operations/nameAndEmailBase64u.js
- packages/mail/lib/updateMergeFields.js
- packages/mail/lib/updateNewsletterSubscription.js
- packages/mail/lib/updateNewsletterSubscriptions.js
- packages/mail/script/mailchimp/checkBatch.js
- packages/mail/script/mailchimp/runOperations.js
- servers/republik/graphql/resolvers/_mutations/updateMe.js
- servers/republik/modules/crowdfundings/graphql/resolvers/_mutations/updateUser.js
- servers/republik/modules/crowdfundings/lib/Mail.js
This Pull Requests updates first and last name merge fields (`FNAME`, `LNAME`) on MailChimp whenever there is a chance of a change, as well as email base64 url-safe encoded merge field (`EMAILBASE64U`).
It also helps updating MailChimp data in batches. You can run individual "operation types" with
```
$ packages/mail/script/mailchimp/runOperations.js --type nameAndEmailBase64u
```
Operation types can be extended in packages/mail/lib/operations and available thus far are:
- `covidAccessToken` to updated Authorize Session Access Tokens in lieu of COVID-19 newsletter
- `nameAndEmailBase64u` to updated name and email base64u fields
Batches can take several hours to complete. Run `runOperations.js --no-interval` to end script once batch is submitted and a batch can be checked manually:
```
$ …
```
> Expand MailChimp Sync

- packages/embeds/lib/youtube/index.js
This Pull Request picks thumbnail with most area. It becomes unaware of what sizes (or size names) YouTube's API is returning.
> fix(embeds): Pick thumbnail with most area

- packages/discussions/lib/Notifications.js
- packages/subscriptions/graphql/schema-types.js
- fix: allow empty Subscription.object (unpublished)
- fix: hide notificationContent.body and url
- cleanup discussion notifications
The majority of changed lines are attributed to the last point.
> handle unpublished notification objects

- servers/republik/graphql/schema-types.js
- servers/republik/lib/MembershipStats/evolution.js
- servers/republik/script/MembershipStats/evolution/evaluate.js
* ended, expired, cancelled, active returning up-to-now in current month,
end of month of past months
* endedEndOfMonth, expiredEndOfMonth, cancelledEndOfMonth returning presumable state at end of month
Also add script to evaluate data without popuplating cache
> feat(republik): Extend MembershipStats.evolution

- servers/publikator/lib/cache/search.js
- servers/publikator/lib/cache/upsert.js
`doc.content` (Markdown MDAST) is split into title, subject, lead, credits and text.
`mdastContentToString` began excluding TITLE identifiers in ab4d1d5 and thus removed e. g. credit line from stringified content and started hindered searching for terms in credit line.
Also search in `shortTitle` and remove weighting on `contentMeta.title`.
> fix(publikator): Split content into multiple strings and query them

- .env.example
- app.json
- packages/translate/translations.json
- servers/publikator/.env.example
- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/lib/mailchimp/createCampaign.js
- servers/publikator/lib/mailchimp/index.js
- servers/publikator/lib/mailchimp/updateCampaign.js
- servers/publikator/lib/mailchimp/updateCampaignContent.js
Use `MAILCHIMP_CAMPAIGN_CONFIGS` to set configurations, containing array with objects.
Each object may contain:
- key, currently format.meta.repoId)
- list_id, MailChimp List ID
- saved_segment_id, MailChimp Segment ID
- to_name, MailChimp Merge Vars as To: name
- from_name, sender From: name
- reply_to, sender email
Publish mutation checks if key matches format.meta.repoId and merges configuration.
This includes fixes:
* Neater error handling if MailChimp fetch request fails or returns errorneous status
* Updated subject line or title will be pushed to MailChimp which it did before only when creating
* From: defaults to DEFAULT_MAIL_FROM_NAME and DEFAULT_MAIL_ADDRESS
Example value in `MAILCHIMP_CAMPAIGN_CONFIGS`
```json
[
{
"key": "republik-dev/format-newsletter-um-7",
"from_name": …
```
> feat(publikator): Configure MailChimp campaign segment, envelope via configs ENV var

- packages/base/lib/Redis.js
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/cache.js
- packages/search/package.json
- yarn.lock
don't expire the search cache key at all (especially not on every GET :facepalm:)
- we flush the cache on publish which happens often (daily)
- we run eviction policy: volatile-lru, let it take care of overspill
- the data doesn't expire, old is valid, no need for redis to check
- we don't need to keep the cache small and want to cache aggressively
new functions behind ENVs:
`SEARCH_CACHE_QUERY`: caches the query to the result into redis (for investigation)
`SEARCH_CACHE_DISABLE`: bypass redis caching of document (elasticsearch) queries completely
`SEARCH_CACHE_COMPRESSION`: compresses the redis payload with https://github.com/kesla/node-snappy (sadly https://github.com/pierrec/node-lz4 is unmaintained). Changing this value requires invalidation of all `search:cache` keys in redis. After …
> redis search cache optimizations and knobs

- servers/republik/modules/crowdfundings/graphql/resolvers/_queries/cancellationCategories.js
This Pull Request hides cancellation category `UNCERTAIN_FUTURE` in `query cancellationCategories` per default.
It is listed when `showMore` argument is truthy (for Admin-Tool and book keeping reasons).
> fix(crowdfundings): List UNCERTAIN_FUTURE when showMore flag is truthy

- Procfile
- Procfile-dev
- package.json
- servers/assets/nodemon.json
- servers/assets/package.json
- servers/publikator/index.js
- servers/publikator/nodemon.json
- servers/publikator/package.json
- servers/publikator/scheduler.js
- servers/publikator/server.js
- servers/republik/index.js
- servers/republik/nodemon.json
- servers/republik/package.json
- servers/republik/scheduler.js
- servers/republik/server.js
Untagles running schedulers from the webserver.
For prod: `server/xxx/index.js` doesn't exec `server.js`'s `runOnce` anymore. A `Procfile` was added which specifies the `web` and `scheduler` task. `web` starts `Server.run`, `scheduler` starts `Server.runOnce`
For dev: As a `Procfile-dev` already exists, only the addition of the new scripts was needed.
> refactor: schedulers

- packages/discussions/lib/Notifications.js
- packages/translate/translations.json
Fixes double quotes in notification titles, e.g.
> fix: quotes in notification titles

- packages/search/lib/inserts/document.js
- packages/search/lib/inserts/repo.js
- packages/translate/translations.json
- servers/publikator/graphql/resolvers/Meta.js
- servers/publikator/graphql/resolvers/Repo.js
- servers/publikator/graphql/resolvers/_mutations/archive.js
- servers/publikator/graphql/resolvers/_mutations/commit.js
- servers/publikator/graphql/resolvers/_mutations/editRepoMeta.js
- servers/publikator/graphql/resolvers/_mutations/publish.js
- servers/publikator/graphql/resolvers/_mutations/unpublish.js
- servers/publikator/graphql/resolvers/_queries/repo.js
- servers/publikator/graphql/resolvers/_queries/reposSearch.js
- servers/publikator/lib/PublicationScheduler.js
- servers/publikator/lib/cache/search.js
- servers/publikator/lib/github/index.js
make repo overview, commits tree and milestones available even if github is unavailable
new redis cache, which is only used if github doesn't answer
- commits (heads)
- annotatedTags
use repo cache for single repo lookup (repo query)
throw error if github is not accessible and cache not available
> feat: github downtime resilience

- packages/republik/modules/crowdfundings/lib/payments/stripe/addSource.js
resolves an error if a stripe customer has no sources (because they were deleted in the stripe dashboard for example)
```
2020-08-20T09:59:22.385619+00:00 app[web.1]: graphql error in undefined (undefined): [GraphQLError [Object]: Cannot read property 'data' of undefined] {
2020-08-20T09:59:22.385620+00:00 app[web.1]: locations: [ { line: 2, column: 3 } ],
2020-08-20T09:59:22.385620+00:00 app[web.1]: path: [ 'addPaymentSource' ],
2020-08-20T09:59:22.385621+00:00 app[web.1]: extensions: {
2020-08-20T09:59:22.385621+00:00 app[web.1]: code: 'INTERNAL_SERVER_ERROR',
2020-08-20T09:59:22.385621+00:00 app[web.1]: exception: {
2020-08-20T09:59:22.385621+00:00 app[web.1]: stacktrace: [
2020-08-20T09:59:22.385622+00:00 app[web.1]: "TypeError: Cannot read property 'data' of undefined", …
```
> fix: stripe customer without sources

- packages/republik/lib/MembershipStats/evolution.js
This error is periodically thrown.
While this be fixed at its root cause, having an error message telling how the error can be mitigated seems like a good idea.
PS: I just lost an hour trying to understand this bug.
> Better error message

- packages/collections/graphql/resolvers/User.js
- packages/collections/graphql/schema-types.js
- packages/collections/lib/Collection.js
Allowing to query `collectionItems` from multiple collections at the same time.
Example query:
```
{
me {
collectionItems(names: ["bookmarks", "progress"], first: 10) {
totalCount
nodes {
id
collection {
name
}
document {
meta {
title
}
}
}
}
}
}
```
> Collection Items

- packages/subscriptions/graphql/resolvers/_queries/notifications.js
- packages/subscriptions/graphql/schema.js
Allow to query for notifications for a specific type.
```gql
{
notifications(first: 2, filter: Document) {
totalCount
nodes {
object {
... on Document {
id
meta {
title
}
}
}
}
}
}
```
> feat(notifications): filter for EventObjectType

- packages/collections/graphql/resolvers/User.js
- packages/collections/graphql/schema-types.js
- packages/collections/lib/Collection.js
- packages/search/lib/Documents.js
- packages/slack/lib/SlackGreeter.js
For continue reading we want to do this:
```gql
{
me {
id
name
collectionItems(names: ["bookmarks", "progress"], progress: UNFINISHED) {
totalCount
nodes {
document {
meta {
title
}
userProgress {
percentage
}
}
}
}
}
}
```
And for a new bookmark page we also want to displayed finished items:
```gql
{
me {
id
name
collectionItems(names: ["progress"], progress: FINISHED) {
totalCount
nodes {
document {
meta {
title
}
userProgress {
percentage
}
}
}
}
}
}
```
The bot unfortunately sends messages as attachments. Let's support that. And also ignore threaded messages going forward, was never supported on purpose.
Currently if an author has a private profile we don't resolve the username. E.g. [here](https://www.republik.ch/2020/09/21/die-waechter-aus-dem-weissen-haus). Let's change that.
> Three Small Things

- packages/auth/graphql/resolvers/User.js
- packages/auth/lib/Roles.js
Returns only exposable roles as defined in [lib/Roles](https://github.com/orbiting/backends/compare/pae/fix-filtered-user-roles?expand=1#diff-92181c7cbf69ecc6d962e11749cbfd07b2ba631beb5e5797b5e319fe3d21bd8dR5-R16). This omits undefined roles like "foobar".
> fix(auth): Filter User.roles

- packages/maillog/graphql/resolvers/User.js
- packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
Merges mail log of source user to target user more diligently. It also fixes a bug on `User.mailLog` which did not return mail log records with only a matching `userId`.
This Pull Request fixes:
- Mutation `mergeUser` sets `mailLog` records with `email` but no `userId` to target user ID thus transferring mail log records (without user ID) to target user.
- `User.mailLog` will return `mailLog` records either linked via `userId` or lacks `userId` but matches current user email address.
- Prevent error if previewRequests table is not available is it was removed a while ago and running migrations on an empty database won't create that table.
Relates to https://github.com/orbiting/backends/issues/506
> Fix User.mailLog and mergeUser mutation

- packages/republik-crowdfundings/lib/payments/paymentslip/sendPaymentReminders.ts
- packages/republik-crowdfundings/lib/scheduler/importPayments.ts
This Pull Request:
- [prevents Array.reduce error if no payments ought to be inserted](https://github.com/orbiting/backends/commit/3895b54c55dff12a5b2f3669e6351e6c10a0ce13)
- [removes call-to-action on highly overdue payments](https://github.com/orbiting/backends/commit/0ecb1cf5ab1287d25b22e3759b8dbd89a5fb7044)
> Fix Postfinance import

- packages/republik-crowdfundings/lib/payments/paymentslip/helpers.ts
- packages/republik-crowdfundings/lib/payments/paymentslip/sendPaymentReminders.ts
This Pull Requests prevents sending payment reminders if most recent Postfinance payment import is older than 12 hours.
> Postfinance reminder prevent

- .env.example
- packages/base/package.json
- packages/base/server.js
Useful to test how applications using this API react on slow responses.
> feat(base): Delay request processing w/ REQ_DELAY_MS in development

- packages/discussions/graphql/resolvers/_mutations/featureComment.js
- packages/discussions/graphql/resolvers/_queries/comments.js
- packages/discussions/graphql/schema-types.js
- packages/discussions/graphql/schema.js
- packages/discussions/lib/Comment/index.js
- packages/discussions/lib/slack.js
- packages/discussions/migrations/sqls/20201202033331-comment-featured-targets-down.sql
- packages/discussions/migrations/sqls/20201202033331-comment-featured-targets-up.sql
- packages/migrations/migrations/20201202033331-comment-featured-targets.js
This Pull Request allows to specify one or more targets a featured comment is aiming for and query for either target.
Available targets (`enum CommentFeaturedTarget`) thus far:
- `DEFAULT`
- `MARKETING`
A featured comment returns its targets on `Comment.featuredTargets`. If a comment is not featured, `Comment.featuredTargets` returns `null`.
**Mutations**
Mutation to feature a comment accepts no, one or more targets:
```gql
mutation featureCommentMutation($commentId: ID!, $content: String, $targets: [CommentFeaturedTarget!]) {
featureComment(id: $commentId, content: $content, targets: $targets) {
id
__typename
}
}
```
Providing no target will set `DEFAULT` as to prevent "targetless" featured comments.
**Queries**
Query for featured comments for Marketing purposes:
```gql
query …
```
> feat(discussions): Introduce featured targets

- packages/republik-crowdfundings/graphql/resolvers/Pledge.js
- packages/republik-crowdfundings/graphql/resolvers/_mutations/submitPledge.js
- packages/republik/graphql/resolvers/User.js
For aborted PostFinance and PayPal transaction I need to be able to query `firstName`, `lastName` and `shippingAddress` when not signed in.
Also changes `submitPledge` to skip `emailVerify` if a user only has draft pledges (e.g. an aborted PostFinance pledge).
> Fix Draft Exposure

- packages/documents/graphql/resolvers/Document.js
- packages/documents/lib/modifiers/index.js
- packages/documents/lib/modifiers/mergePropsWhenUserHasSomeRole.js
- packages/documents/lib/process.js
This Pull Request is probably my most accomplished achievement.
A reviewer might want to freshen-up on [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is it is used extensivly.
This Dynamic Component config …
```json
{
"props": {
"foo": "bar"
},
"src": "url-to-component",
"modifiers": [
{
"name": "mergePropsWhenUserHasSomeRole",
"props": {
"additional": "additional-prop-when-user-has-member-role"
},
"roles": [
"member"
]
}
]
}
```
… should return when user is in member role:
```json
{
"props": {
"foo": "bar",
"additional": "additional-prop-when-user-has-member-role"
},
"src": "url-to-component"
}
```
… should return when user has no member role:
```json
{
"props": {
"foo": "bar"
},
"src": "url-to-component"
}
```
> feat(documents): Process node modifiers

- packages/discussions/graphql/resolvers/Comment.js
- packages/translate/translations.json
This Pull Request will hide (`displayAuthor`) or default `Comment` props (`upVotes`, `downVotes`). It also forwards `Comment.adminUnpublished` prop untarnished.
> Hide or default props data on unpublished nodes

- .env.example
- packages/mail/lib/sendMail.js
- packages/mail/lib/sendMailTemplate.js
This Pull Request will prepend environment variable `SEND_MAILS_SUBJECT_PREFIX` to all transactional email subject lines. It should help recognize development, test and staging emails.
Example:
- `SEND_MAILS_SUBJECT_PREFIX=Test` will send email «Am 15.01.2021 erneuert sich Ihre Mitgliedschaft» as «[Test] Am 15.01.2021 erneuert sich Ihre Mitgliedschaft»
> feat(mail): Add subject prefix

- .env.example
- packages/discussions/graphql/resolvers/Discussion/userWaitUntil.js
- packages/discussions/graphql/resolvers/DiscussionSuspension.js
- packages/discussions/graphql/resolvers/User.js
- packages/discussions/graphql/resolvers/_mutations/submitComment.js
- packages/discussions/graphql/resolvers/_mutations/suspendUser.js
- packages/discussions/graphql/resolvers/_mutations/unsuspendUser.js
- packages/discussions/graphql/schema-types.js
- packages/discussions/graphql/schema.js
- packages/discussions/lib/slack.js
- packages/discussions/loaders/DiscussionSuspension.js
- packages/discussions/loaders/index.js
- packages/discussions/migrations/sqls/20201218010032-user-suspensions-down.sql
- packages/discussions/migrations/sqls/20201218010032-user-suspensions-up.sql
- packages/migrations/migrations/20201218010032-user-suspensions.js
- packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
This Pull Request ought to replace `DISCUSSION_BANS` environment variable.
It allows to suspend via GraphQL mutations if current user has admin or supporter role:
```gql
mutation {
suspendUser(id:"some-user-uuid" until:"2021-05-05") {
suspendedUntil
}
}
```
One might also want to revert a suspension prematurly with `unsuspendUser`:
```gql
mutation {
unsuspendUser(id:"some-user-uuid") {
isSuspended
}
}
```
A suspended user is unable to post a new comment.
User data is extend with these props, accessible for user itself or user with admin or supporter role:
- `User.isSuspended: Boolean`, indicates whether or not a user is currently suspended
- `User.suspendedUntil: DateTime`, indicates until when a user is suspended
- `User.suspensions: [DiscussionSuspension!]`, returns a list of current …
> refactor(discussions): Replace ban environment variable w/ suspensions table

- packages/mail/templates/membership_cancel_notice.html
- packages/mail/templates/membership_cancel_notice.txt
- packages/republik-crowdfundings/graphql/resolvers/_mutations/cancelMembership.js
- packages/republik-crowdfundings/lib/Mail.js
This Pull Request enables switch in `membership_cancel_notice` template. It indicates whether membership is cancelled but remains active until last day, or is disabled at once.
> Cancel notice w/ immediate deactivation phrase

- packages/invoices/lib/paymentslip.ts
- packages/republik-crowdfundings/lib/scheduler/payments/fixtures/camt053mitteilung.xml
- packages/republik-crowdfundings/lib/scheduler/payments/fixtures/camt053reference.xml
- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.ts
- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.u.jest.ts
This Pull Request ensures simple HR-IDs (`AABBCC`) are trumped by creditor references (`RF12HRID…`), will allow for padded creditor references (`RF1200000000HRID…`) and adds tests to this effect.
> Fix parse creditor references

- packages/mail/templates/membership_deactivated_abo_give_months_uncancelled.html
- packages/mail/templates/membership_deactivated_abo_give_months_uncancelled.txt
- packages/mail/templates/membership_owner_prolong_abo_give_months_notice_0.html
- packages/mail/templates/membership_owner_prolong_abo_give_months_notice_0.txt
- packages/republik-crowdfundings/graphql/resolvers/User.js
- packages/republik-crowdfundings/lib/scheduler/owners.js
- packages/translate/translations.json
Add some transactional templates for membership type `ABO_GIVE_MONTHS`, sends T+0 `membership_owner_prolong_abo_give_months_notice_0`. Other template is send when membership is deactivated.
It removes `ABO_GIVE_MONTHS` early exit on `User.prolongBeforeDate` resolver and will thus return a date for `ABO_GIVE_MONTSH` memberships, too.
⚠️ This change impacts current version of [republik-frontend](https://github.com/orbiting/republik-frontend/tree/903dcbb310829affba633fc4c2b4899e8dd5b270). Changes suggested [here](https://github.com/orbiting/republik-frontend/pull/530).
> Add T+0, T+14 templates for ABO_GIVE_MONTHS

- packages/migrations/migrations/20210118041504-user-addressid-ondelete-setnull.js
- packages/republik-crowdfundings/graphql/resolvers/_mutations/mergeUsers.js
- packages/republik/migrations/crowdfunding/sqls/20210118041504-user-addressid-ondelete-setnull-down.sql
- packages/republik/migrations/crowdfunding/sqls/20210118041504-user-addressid-ondelete-setnull-up.sql
This Pull Request fixes two bugs:
- Skip creating questionnaireSubmissions, merging answers. If there is no answers, it should no longer produce error: `Invalid conditions! empty array for field:"questionnaireId" and operator:"= ANY"`
- Set `users.addressId` to `NULL` if referenced address row is deleted. It should no longer attempt to delete user when deleting address row.
> Fix mutation mergeUsers

- packages/invoices/lib/paymentslip.ts
- packages/republik-crowdfundings/lib/scheduler/payments/fixtures/camt053mitteilung.xml
- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.ts
- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.u.jest.ts
This Pull Request hardens reference using case-insensitive search and checking `avisierungstext` if no remittance information is available.
> fix(invoices): Harden reference parsing

- packages/auth/lib/AccessToken.js
- packages/formats/index.d.ts
- packages/invoices/express/index.ts
- packages/invoices/index.ts
- packages/invoices/lib/commons.ts
- packages/invoices/lib/invoice.ts
- packages/invoices/lib/paymentslip.ts
- packages/invoices/package.json
- packages/migrations/migrations/20210127094404-bank-account-invoicing.js
- packages/republik-crowdfundings/graphql/resolvers/PledgePayment.js
- packages/republik-crowdfundings/graphql/schema-types.js
- packages/republik-crowdfundings/lib/Mail.js
- packages/republik-crowdfundings/lib/payments/paymentslip/sendPaymentReminders.ts
- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.ts
- packages/republik/migrations/crowdfunding/sqls/20210127094404-bank-account-invoicing-down.sql
- packages/republik/migrations/crowdfunding/sqls/20210127094404-bank-account-invoicing-up.sql
- packages/translate/translations.json
- yarn.lock
This Pull Request can generate an invoice or receipt. [It includes a "Swiss QR Bill" if applicable](https://github.com/orbiting/backends/pull/552).
Using a scoped access token (`INVOICE`) and HR-ID, API will provide an invoice or receipt via URL as PDF if token and HR-ID eventually belong to same user. It requires a payment to be in status `PAID` or `WAITING`. Example: `/invoices/[HR-ID].pdf?token=[Access Token]`
PDFs are generated on the fly and neither cached nor stored. Over time, contents of a payment slip might change, i. e. a user updates their address.
GraphQL returns a payment slip URL on `PledgePayment.invoiceUrl` if user holds roles `admin` or `supporter`: Example:
```gql
{
me {
pledges {
payments {
invoiceUrl
}
}
}
}
```
> Invoices and receipts

- packages/migrations/migrations/20210201080354-base.js
- packages/publikator/migrations/sqls/20210201080354-base-down.sql
- packages/publikator/migrations/sqls/20210201080354-base-up.sql
Includes schema for repos, commits and milestones, adds triggers and
alters notifyTableChangeQueue to accept ids as text (instead of uuids)
> feat(publikator): Add base migrations

- packages/mail/templates/payment_successful_benefactor.html
- packages/mail/templates/payment_successful_benefactor.txt
- packages/mail/templates/pledge_benefactor.html
- packages/mail/templates/pledge_benefactor.txt
* golden pins are not sent via mail anymore so it's removed from mail templates
> fix(mail) remove golden pin from benefactor payment and pledge mail

- packages/publikator/lib/cache/search.ts
Path to field is `commit.meta.title`, not `meta.title`.
> fix(publikator): Fix field path to search meta.title in

- packages/assets/lib/urlPrefixing.js
- packages/assets/lib/urlPrefixing.u.jest.js
- packages/documents/graphql/resolvers/Document.js
- packages/documents/lib/process.js
- packages/embeds/lib/fetchAndStore.js
- packages/publikator/graphql/resolvers/Commit.js
- packages/publikator/graphql/resolvers/_mutations/commit.js
This Pull Request updates url prefixing and mdast node processing.
Mdast node processing becomes asynchrounsly (`packages/documents/lib/process.js`). It allows to fetch and upload images in process section while comitting.
Mdast node processing is now only code aware what nodes to alter and how. This also makes for a more readable `packages/publikator/graphql/resolvers/_mutations/commit.js`.
> refactor: Clean-up url prefixing and mdast node processing

- packages/mail/lib/sendMailTemplate.js
- packages/publikator/loaders/Commit.ts
- packages/publikator/loaders/Milestone.ts
- packages/publikator/loaders/Repo.ts
Subscriptions do not pair well with dataloaders. A dataloader is instantiated on subscribe event and kept until subscribtion ends – including in-memory response cache.
While regular request complete in a bearable amount of time, subscription may last for hours and hence an in-memory cache.
As a trade-off solution, this commit disables cache for dataloaders in publikator/loaders (but keeps batching functionality).
> fix(publikator): Disable dataloader cache but keep batching 

- packages/publikator/lib/Document.js
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/indices/documents.js
This is a non-breaking change.
- Refrain from boosting whenever possible.
- Indexes headlines (title, short title and similar) with stopwords.
- Series or long-reads won't over-power results anymore.
- Instead of demoting newsletter we boost "primary" templates: articles, formats and dossier.
- Includes series title in fields searched
Fixes https://github.com/orbiting/backends/issues/492
> Improve search ranking

- packages/republik-crowdfundings/lib/scheduler/payments/parseCamt053.ts
Co-authored-by: Sharon Funke <fuenkchen@users.noreply.github.com>
Fixes
```
importPayments(): postfinance sync failed with the following error:
invalid input syntax for type integer: "7040.000000000001"
```
> fix(republik-crowdfundings): Ensure toCents returns an integer value

- packages/statistics/script/matomo/collect.js
- packages/statistics/script/matomo/index.js
- packages/statistics/script/report/daily.js
[yargs breaking change](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#1700-2021-05-02) applies coerce before validation, thus all date fields are set.
Fix favors relative date over range or absolut date. If not set, relative date is falsy.
> fix(statistics): Favor relative date over date range or absolute date

- packages/mail/MailchimpInterface.js
- packages/mail/lib/moveNewsletterSubscriptions.js
solves #276
Changes are as follows and can be tested on love
- added new method to MailchimpInterface to permanently delete member in Mailchimp
- if a user is deleted, the corresponding email address will be deleted (instead of archived) in Mailchimp
- if two users are merged, the old email address will be archived (instead of unsubscribed) in Mailchimp
- if the email address of a user is changed, the old email address will be archived (instead of unsubscribed) in Mailchimp
> changes to MailchimpInterface

- packages/access/lib/grants.js
- packages/access/lib/memberships.js
- packages/access/lib/perks/accessWithRole.js
- packages/access/lib/perks/index.js
- packages/translate/translations.json
Can be tested on love
* for editors, supporters and admins a new access campaign should appear at `/teilen``
* after granting access recipient should receive invitation mail, after claiming access, granter should receive confirmation mail
* the role `debater` should be added to recipient
When deploying we need to execute the an SQL statement to add suitable access campaign, can be reviewed as well :)
```
INSERT INTO "accessCampaigns"("title","description","grantPeriodInterval","emailFollowup","beginAt","endAt","constraints","createdAt","updatedAt","grantClaimableInterval","config")
VALUES
('Autorinnen im Dialog 🦄','Abonnement teilen, um externen Autoren einen 21-tägigen Zugriff und die Möglichkeit zu geben, aktiv am Dialog teilzunehmen.','21 days','7 days','2021-06-28 …
```
> Add perk to share access with debater role

- docker-compose.yml
- packages/base/lib/Elasticsearch.js
- packages/base/package.json
- packages/publikator/graphql/resolvers/_queries/reposSearch.js
- packages/publikator/lib/cache/search.ts
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/Documents.js
- packages/search/lib/filters.js
- packages/search/lib/pullElasticsearch.js
- yarn.lock
This Pull Request allows us to use ElasticSearch 7.
Major change: In ElasticSearch 6, `hits.total` is an integer. In ElasticSearch 7, `hits.total` [is an object](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/breaking-changes-7.0.html#hits-total-now-object-search-response), returning document count as `value` and `relation` of count. We use `track_total_hits` flag [to get an accurate (but "costly") document count](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-your-data.html#track-total-hits).
Bugfix: We may have passed a filter array containing objects and arrays with objects. While ElasticSearch prior to version 7 was lenient on this, version 7 isn't anymore and will throw a parsing exception.
Fixes #616
> ElasticSearch 7 compatibility

- .env.example
- packages/publikator/graphql/resolvers/_queries/reposSearch.js
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/lib/utils.js
This Pull Request fixes a but which lead to bloated pagination cursors. Each page appended same `SearchInputFilter` to cursor again and again.
It also stabilizes cursors be ignore other options (e.g. different search term) once a cursor is provided.
It further removes tracking of search requests. Once designated to improve search results eventually, that feature was abanonded soon after its release and it got never reinstated.
> Prevent cursor bloating and stabilize cursor

- packages/assets/lib/Portrait.js
- packages/republik/graphql/resolvers/_mutations/updateMe.js
If `checkUsername` or database transaction failed, current portrait was deleted but new portrait never linked. It will delete new portrait if transaction failed as to not have any dead files.
> fix(republik): Delete portrait asset after db tx

- packages/republik-crowdfundings/graphql/resolvers/_mutations/reactivateMembership.js
- packages/republik-crowdfundings/lib/payments/stripe/reactivateSubscription.js
This Pull Request fixes a regression introduced in #522: Mutation `reactivateMembership` did no reactive cancelled but still active subscriptions.
API version 2018-02-28 or younger require `cancel_at_period_end` parameter to reactive a cancelled (but active) subscription.
Before #522 we used API version 2017-12-14 which "[any parameter sent to the Update Subscription API would automatically reactivate a subscription.](https://stripe.com/docs/billing/subscriptions/cancel#reactivating-canceled-subscriptions)"
> fix(republik-crowdfundings): Reactivate cancelled but active subscription

- packages/republik-crowdfundings/graphql/resolvers/_mutations/reactivateMembership.js
- packages/republik-crowdfundings/lib/payments/stripe/Errors.js
- packages/republik-crowdfundings/lib/payments/stripe/createSubscription.js
- packages/republik-crowdfundings/lib/payments/stripe/payPledge.js
- packages/translate/translations.json
This Pull Requests enforces [no deferred payment confirmation (e.g. 3DS) when reactivating a subscription](https://github.com/orbiting/backends/commit/aebcf99a0f5ce8861ed4de5a9ede9d1a084fb109). 
It also handles reactivation errors similar to errors while paying a pledge.
> fix(republik-crowdfundings): Throw error if payment_intent fails

- packages/documents/graphql/resolvers/DocumentZone.js
- packages/documents/graphql/schema-types.js
- packages/search/graphql/resolvers/_queries/search.js
- packages/search/graphql/schema-types.js
- packages/search/lib/DocumentZones.js
- packages/search/lib/Documents.js
- packages/search/lib/aggregations.js
- packages/search/lib/filters.js
- packages/search/lib/indices/documentzones.js
- packages/search/lib/indices/index.js
- packages/search/lib/inserts/document.js
- packages/search/lib/inserts/documentzone.js
- packages/search/lib/inserts/index.js
This Pull Request indexes document zones and makes them somewhat searchable.
In this iteration, it only indexes zones with identifier `CHART`.
Zones are stringified – that is title, lead, credits –, and these strings are searchable.
New filters:
- `{ key: "type" value:"DocumentZone" }`: returns zones
- `{ key: "documentZoneIdentifier" value:"CHART" }`: returns all charts
- `{ key: "documentZoneDataType" value:"Bar" }`: returns all bar charts
Document zones are indexed upon publish.
(Search entity, aggregations)
> Index document zones

- .gitignore
- packages/auth/express/auth.js
- packages/auth/loaders/User.ts
- packages/mailbox/README.md
- packages/mailbox/graphql/index.js
- packages/mailbox/graphql/resolvers/MailboxAddress.js
- packages/mailbox/graphql/resolvers/User.js
- packages/mailbox/graphql/resolvers/_queries/mailbox.js
- packages/mailbox/graphql/schema-types.js
- packages/mailbox/graphql/schema.js
- packages/mailbox/index.js
- packages/mailbox/lib/common.js
- packages/mailbox/lib/index.js
- packages/mailbox/lib/mailbox.js
- packages/mailbox/lib/maillog.js
- packages/mailbox/lib/search.js
- packages/mailbox/package.json
- packages/maillog/graphql/schema-types.js
- packages/maillog/graphql/schema.js
- packages/search/lib/indices/index.js
- packages/search/lib/indices/mails.js
- packages/search/lib/inserts/index.js
- packages/search/lib/inserts/mail.js
- packages/utils/paginate.js
- servers/graphql/server.js
- yarn.lock
This Pull Request adds [`mailbox` queries to root and `User.mailbox`](https://github.com/orbiting/backends/compare/pae/feat-zat?expand=1#diff-69df5e7dfca0bc0e0a1ef244a5233a9571ec27938974adbf1ee28238159cbf83) to query (new) mail index and `mailLog` table at once and thus [deprecating `mailLog` queries](https://github.com/orbiting/backends/compare/pae/feat-zat?expand=1#diff-b941647b52246b2ad69ba7b26189886545bea78af20782344e25adcbc6e7992f).
It changes [session cookie attribute `SameSite` to `None`](https://github.com/orbiting/backends/compare/pae/feat-zat?expand=1#diff-192366cb64dcd51bed8ffd63a9aaddc48d8fee59d907daa1e7f553ed9bc0abc2) if not in production. (This might pose an inadvertent security risk and we've to dig into that one deeper.)
It implements a [new pagination approach …
> Mailbox queries, cookie SameSite=None and "pageini"

- packages/mail/templates/election_candidacy_confirmation_gen21m.html
- packages/mail/templates/election_candidacy_confirmation_gen21m.txt
- packages/migrations/migrations/20210818173518-election-candidacies-credential.js
- packages/migrations/migrations/20210819162118-user-gender.js
- packages/republik/graphql/resolvers/User.js
- packages/republik/graphql/resolvers/_mutations/updateMe.js
- packages/republik/graphql/schema-types.js
- packages/republik/graphql/schema.js
- packages/republik/migrations/sqls/20210819162118-user-gender-down.sql
- packages/republik/migrations/sqls/20210819162118-user-gender-up.sql
- packages/translate/translations.json
- packages/voting/graphql/resolvers/Candidacy.js
- packages/voting/graphql/resolvers/_mutations/submitCandidacy.js
- packages/voting/graphql/schema-types.js
- packages/voting/graphql/schema.js
- packages/voting/lib/Candidacy.js
- packages/voting/migrations/sqls/20210818173518-election-candidacies-credential-down.sql
- packages/voting/migrations/sqls/20210818173518-election-candidacies-credential-up.sql
TODOs:
maybe there are some more things needed to implement / finalize frontend
> Feat election candidacy

- packages/discussions/graphql/resolvers/Discussion/comments.js
- packages/discussions/graphql/resolvers/_queries/comments.js
- packages/discussions/graphql/schema-types.js
* adds `AUTO` to `DiscussionOrder` enum in schema
* adds `resolvedOrderBy` property to `CommentConnection` in schema
* when auto sorting is requested in Discussion.comments it will check creation date of first comment:
* if it's within the last 24 hours it will sort by `DATE`
* if it's older than 24 hours it will sort by `VOTES`
* and returns it as `resolvedOrderBy`
can be tested on love
> auto sorting of discussion comments

- packages/mail/MandrillInterface.js
- packages/mailbox/lib/maillog.js
Throws a little more verbose errors when using Mandrill to send an email fails.
> fix(mail): Throw more verbose error

- packages/utils/__snapshots__/mdastCollapseLink.u.jest.js.snap
- packages/utils/mdastCollapseLink.js
- packages/utils/mdastCollapseLink.u.jest.js
`child.value` is not always present in MDAST when formatting a link itself. In such cases, do not collapse link.
> fix(utils): Harden against missing value

- packages/documents/graphql/schema-types.js
Publikator introduces new seo fields which also should be exposed via graphql:
https://github.com/orbiting/publikator-frontend/pull/302
@patrickvenetz do you want to add the fields to our elastic index? Maybe we should also add twitter title and lead then? Will be used for search engines if seo fields are not filled.
> feat(Document): resolve meta seo title and seo description

- packages/publikator/graphql/resolvers/_mutations/commit.js
- packages/publikator/graphql/resolvers/_queries/reposSearch.js
- packages/publikator/graphql/schema.js
- packages/publikator/lib/cache/search.ts
- packages/translate/translations.json
This Pull Request will throw an error on commit if overiew points to anything but a series master document. It also allows to search for repos on which last commit indicates a series master or episode document.
Each document in a series should point to a series master.
In a master document, `meta.series.overview` should contain a repo URL (and is usually a self-reference). In an episode document, `meta.series` should contain a repo URL.
`meta.series` is either an object (when master) or a string (when episode).
`repoSearch` can query for `isSeriesMaster` or `isSeriesEpisode`.
> fix: Check overview is linked to a series master

- packages/publikator/graphql/resolvers/_mutations/publish.js
This Pull Request changes publish mutation. Mutation should only handle redirections if document is published immediatly. (Publication scheduler will take care of redirection handling for scheduled publications.)
It fixes a bug which pointed existing redirection records to a not-yet-published document.
> fix(publikator): Handle redirections only if publication is not scheduled

- packages/mail/express/mailchimp.js
- packages/mail/lib/mailLog.js
- packages/mail/package.json
- packages/mail/script/sendMailsToSegment/cleanedUserSubscriptionInvitation.js
- packages/mail/script/sendMailsToSegment/sendMailsToSegment.js
- packages/mail/templates/cleaned_user_subscription_invitation.html
- packages/mail/templates/cleaned_user_subscription_invitation.txt
- yarn.lock
- adds script to send mails to a certain segment of mail addresses
- adds script to get cleaned users and provide specific mail information
- adds mail template for cleaned users to invite them to get back to newsletter subscription
Possible further improvements
- move temporary templates to another location and extend `getTemplates` method so that one could specify a path
- there are some code duplicates in `sendScheduledMails.js` and `sendMailsToSegment.js` - maybe this could be generalized too
- atm one can use `envMergeVars` but cannot specify further vars which will be merged together, this could be done now or whenever it's really needed
- maybe use `queryInBatches` (or as option if number in segment is over certain threshold)
> (mail) cleaned user mail

- packages/republik-crowdfundings/lib/scheduler/index.js
- packages/schedulers/lib/timeScheduler.js
Postfinance is providing payment data Tuesdays to Saturday. This Pull Request won't run import on Sundays and Mondays.
> Run payments import Tuesday to Saturday

- packages/push-notifications/lib/firebase.js
- packages/push-notifications/package.json
`sendToDevice` accepts up to 1000 tokens per call
> fix(push-notifications): Split tokens into chunks of 1000 tokens

- packages/mail/express/mailchimp.js
This is a temporary fix to prevent an undesired race condition with `enforceSubscriptions` in Access Grants.
It reverts https://github.com/orbiting/backends/commit/0134140c13b7c0740ae22e93618b1c784a291bdc partially.
> fix(mail): Revert apply enforceSubscriptions on Mailchimp webhook call

- packages/search/lib/Documents.js
Schedule at is nulled when a newer version get scheduled. But the previous could still have been uploaded to MailChimp. Therefore we can not rely on scheduleAt being present.
Fixes this case:
https://piratinnen.slack.com/archives/C8T08FYFR/p1639837278345600
> fix(search): create redirects independent of scheduleAt

- packages/discussions/graphql/resolvers/_mutations/submitComment.js
If user is not logged in, calling `submitComment` throw and `id is undefined` error because `user` is not defined in context.
This Pull Request fixes that. `Roles.ensureUserHasRole` will throw error if `me` aka. `user` is not defined. If that checked is passed, it is safe to access `me.id`.
> fix(discussions): Remove userId in submitComments

- packages/voting/lib/queries.js
This Pull Request will require either of allowed memberships on a user to be active.
If not, a user with an inactive membership – either used or new – might be eligable to submit a ballot or answer.
> fix(voting): Require allowed membership to be active

- packages/publikator/lib/Document.js
- packages/search/lib/Documents.js
Upserting redirections while publishing let to multiple rows with same `source`. To prevent, this Pull Request switches to `Promise.each` instead of `Promise.all`, and it uniquifies previous paths before upserting.
Adds `findPublications`, which returns all "publication" docs stored in ElasticSearch. These are docs that were once published or scheduled to be published.
We want to generate a redirection record for each publication, since a path in a scheduled publication might have been hardcoded elswhere (e.g. a newsletter) while a path might change again before a scheduled publication is actually published.
(It reverts `findPublished`, as it should return actually published or currently scheduled docs.)
> fix(publikator): Handle redirection upsert sequentially

- packages/assets/lib/returnImage.js
A missing Accept header led to a type error ("Cannot read property 'includes' of undefined").
> fix(assets): Harden "Accept" header check

- packages/assets/lib/returnImage.js
Exit early and send error message as plain text.
Setting "forward filtered headers" once response is send to client (`.end(...)`) will throw an error.
> fix(assets): Return 400 w/ error message on failed resize parsing

- .env.example
- docker-compose.yml
- packages/maillog/migrations/sqls/20220111160117-drop-unused-indices-down.sql
- packages/maillog/migrations/sqls/20220111160117-drop-unused-indices-up.sql
- packages/migrations/migrations/20220111155837-drop-unused-indices.js
- packages/migrations/migrations/20220111160117-drop-unused-indices.js
- packages/publikator/lib/Document.js
- packages/search/lib/indices/comments.js
- packages/search/lib/indices/documents.js
- packages/search/lib/indices/users.js
- packages/search/lib/inserts/documentzone.js
- packages/subscriptions/migrations/sqls/20220111155837-drop-unused-indices-down.sql
- packages/subscriptions/migrations/sqls/20220111155837-drop-unused-indices-up.sql
`heroku pg:diagnose` reports unused Postgres indices `notifications::notifications_event_id_idx` and `mailLog::mail_log_email_lower_idx`. In ElasticSearch mappings on documents, comment and users, some more indices are never used either.
This Pull Request drops these mercilessly.
Other changes include:
- Prefix to path for prepublished documents is exposed as ENV variable `PREFIX_PREPUBLICATION_PATH` (instead of hardcoded).
- For development purposes, one can suppresses downloading and measuring audio files while indexing a document with ENV variable`SUPPRESS_AUDIO_DURATION_MEASURE`.
- Due to licensing changes, ElasticSearch is not publishing an OSS version anymore. 
- Fixes missing Embed dataloader when indexing document zones
> chore: Unused indices in Postgres, ElasticSearch

- packages/auth/graphql/resolvers/_mutations/addUserToRole.js
- packages/auth/graphql/resolvers/_mutations/removeUserFromRole.js
- packages/auth/lib/slack.js
- packages/auth/lib/transformUser.ts
Posts a slack message if mutations `addUserToRole` or `removeUserFromRole` are called.
It also updates `transformUser`: If `_raw` is available, user object has been transformed already and returns early with already transformed user.
> feat(auth): Post slack message on addUserToRole, removeUserFromRole

- .env.example
- packages/republik-crowdfundings/lib/scheduler/owners.js
This Pull Request allows to set concurrency number on membership-owners scheduler, which describes users handled at the same time. It defaults to 10.
> feat(republik-crowdfundings): Put concurrency number in ENV var

- packages/mail/lib/sendMailTemplate.js
- packages/mail/templates/membership_giver_prolong_notice.html
- packages/mail/templates/membership_giver_prolong_notice.txt
- packages/mail/templates/signin_app_notice.html
- packages/mail/templates/signin_app_notice.txt
- packages/translate/translations.json
* with [account revision in frontend](https://github.com/orbiting/republik-frontend/pull/702/) some urls change, this PR updates these urls accordingly 
* fixes some other tiny stuff along the way:
* translation for newsletter settings error
* remove unwanted closing if in mail template
! Deploy note: Do not ship on prod before frontend changes have been deployed
> fix(mail): updated account urls, fix if construct in template
